import type {
  GlobeData,
  GlobeCountry,
  FlowArc,
  GlobeAlert,
  CountryDetailData,
} from "@/types/pulse";

/* ─── Country coordinates (lat/lng for arc endpoints) ─────────── */

const COORDS: Record<string, { lat: number; lng: number; name: string }> = {
  US: { lat: 39.8, lng: -98.5, name: "United States" },
  GB: { lat: 55.4, lng: -3.4, name: "United Kingdom" },
  NG: { lat: 9.1, lng: 8.7, name: "Nigeria" },
  BR: { lat: -14.2, lng: -51.9, name: "Brazil" },
  MX: { lat: 23.6, lng: -102.6, name: "Mexico" },
  DE: { lat: 51.2, lng: 10.5, name: "Germany" },
  FR: { lat: 46.2, lng: 2.2, name: "France" },
  JP: { lat: 36.2, lng: 138.3, name: "Japan" },
  KR: { lat: 35.9, lng: 127.8, name: "South Korea" },
  IN: { lat: 20.6, lng: 78.9, name: "India" },
  ZA: { lat: -30.6, lng: 22.9, name: "South Africa" },
  AU: { lat: -25.3, lng: 133.8, name: "Australia" },
  CO: { lat: 4.6, lng: -74.3, name: "Colombia" },
  AR: { lat: -38.4, lng: -63.6, name: "Argentina" },
  KE: { lat: -0.02, lng: 37.9, name: "Kenya" },
  GH: { lat: 7.9, lng: -1.0, name: "Ghana" },
  PH: { lat: 12.9, lng: 121.8, name: "Philippines" },
  ID: { lat: -0.8, lng: 113.9, name: "Indonesia" },
  EG: { lat: 26.8, lng: 30.8, name: "Egypt" },
  TR: { lat: 39.0, lng: 35.2, name: "Turkey" },
  SE: { lat: 60.1, lng: 18.6, name: "Sweden" },
  ES: { lat: 40.5, lng: -3.7, name: "Spain" },
  IT: { lat: 41.9, lng: 12.6, name: "Italy" },
  CA: { lat: 56.1, lng: -106.3, name: "Canada" },
  NL: { lat: 52.1, lng: 5.3, name: "Netherlands" },
  PL: { lat: 51.9, lng: 19.1, name: "Poland" },
  TH: { lat: 15.9, lng: 100.9, name: "Thailand" },
  VN: { lat: 14.1, lng: 108.3, name: "Vietnam" },
  CL: { lat: -35.7, lng: -71.5, name: "Chile" },
  PE: { lat: -9.2, lng: -75.0, name: "Peru" },
  MA: { lat: 31.8, lng: -7.1, name: "Morocco" },
  SA: { lat: 23.9, lng: 45.1, name: "Saudi Arabia" },
  AE: { lat: 23.4, lng: 53.8, name: "UAE" },
  IL: { lat: 31.0, lng: 34.9, name: "Israel" },
  RO: { lat: 45.9, lng: 24.97, name: "Romania" },
  UA: { lat: 48.4, lng: 31.2, name: "Ukraine" },
  PT: { lat: 39.4, lng: -8.2, name: "Portugal" },
  NO: { lat: 60.5, lng: 8.5, name: "Norway" },
  DK: { lat: 56.3, lng: 9.5, name: "Denmark" },
  FI: { lat: 61.9, lng: 25.7, name: "Finland" },
  IE: { lat: 53.4, lng: -8.2, name: "Ireland" },
  NZ: { lat: -40.9, lng: 174.9, name: "New Zealand" },
  SG: { lat: 1.4, lng: 103.8, name: "Singapore" },
  MY: { lat: 4.2, lng: 101.9, name: "Malaysia" },
  TZ: { lat: -6.4, lng: 34.9, name: "Tanzania" },
  SN: { lat: 14.5, lng: -14.5, name: "Senegal" },
  CI: { lat: 7.5, lng: -5.5, name: "Ivory Coast" },
};

export function getCountryCoords(code: string) {
  return COORDS[code] ?? { lat: 0, lng: 0, name: code };
}

/* ─── Mock countries ──────────────────────────────────────────── */

const mockCountries: GlobeCountry[] = (
  [
    {
      country_code: "US",
      country_name: "United States",
      activity_score: 0.95,
      song_count: 4280,
      platform_count: 7,
      dominant_genre: "hip hop",
      new_entries: 187,
      ...COORDS.US,
    },
    {
      country_code: "GB",
      country_name: "United Kingdom",
      activity_score: 0.88,
      song_count: 2140,
      platform_count: 7,
      dominant_genre: "pop",
      new_entries: 94,
      ...COORDS.GB,
    },
    {
      country_code: "NG",
      country_name: "Nigeria",
      activity_score: 0.82,
      song_count: 372,
      platform_count: 6,
      dominant_genre: "afrobeats",
      new_entries: 23,
      ...COORDS.NG,
    },
    {
      country_code: "BR",
      country_name: "Brazil",
      activity_score: 0.79,
      song_count: 1580,
      platform_count: 6,
      dominant_genre: "latin",
      new_entries: 68,
      ...COORDS.BR,
    },
    {
      country_code: "MX",
      country_name: "Mexico",
      activity_score: 0.76,
      song_count: 1120,
      platform_count: 6,
      dominant_genre: "latin",
      new_entries: 52,
      ...COORDS.MX,
    },
    {
      country_code: "DE",
      country_name: "Germany",
      activity_score: 0.72,
      song_count: 890,
      platform_count: 6,
      dominant_genre: "electronic",
      new_entries: 31,
      ...COORDS.DE,
    },
    {
      country_code: "FR",
      country_name: "France",
      activity_score: 0.71,
      song_count: 850,
      platform_count: 6,
      dominant_genre: "hip hop",
      new_entries: 29,
      ...COORDS.FR,
    },
    {
      country_code: "JP",
      country_name: "Japan",
      activity_score: 0.74,
      song_count: 960,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 44,
      ...COORDS.JP,
    },
    {
      country_code: "KR",
      country_name: "South Korea",
      activity_score: 0.77,
      song_count: 1050,
      platform_count: 5,
      dominant_genre: "k-pop",
      new_entries: 61,
      ...COORDS.KR,
    },
    {
      country_code: "IN",
      country_name: "India",
      activity_score: 0.68,
      song_count: 720,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 38,
      ...COORDS.IN,
    },
    {
      country_code: "ZA",
      country_name: "South Africa",
      activity_score: 0.58,
      song_count: 310,
      platform_count: 5,
      dominant_genre: "afrobeats",
      new_entries: 15,
      ...COORDS.ZA,
    },
    {
      country_code: "AU",
      country_name: "Australia",
      activity_score: 0.65,
      song_count: 540,
      platform_count: 6,
      dominant_genre: "pop",
      new_entries: 22,
      ...COORDS.AU,
    },
    {
      country_code: "CO",
      country_name: "Colombia",
      activity_score: 0.73,
      song_count: 880,
      platform_count: 5,
      dominant_genre: "latin",
      new_entries: 41,
      ...COORDS.CO,
    },
    {
      country_code: "AR",
      country_name: "Argentina",
      activity_score: 0.67,
      song_count: 620,
      platform_count: 5,
      dominant_genre: "latin",
      new_entries: 27,
      ...COORDS.AR,
    },
    {
      country_code: "KE",
      country_name: "Kenya",
      activity_score: 0.45,
      song_count: 180,
      platform_count: 4,
      dominant_genre: "afrobeats",
      new_entries: 12,
      ...COORDS.KE,
    },
    {
      country_code: "GH",
      country_name: "Ghana",
      activity_score: 0.48,
      song_count: 210,
      platform_count: 4,
      dominant_genre: "afrobeats",
      new_entries: 14,
      ...COORDS.GH,
    },
    {
      country_code: "PH",
      country_name: "Philippines",
      activity_score: 0.55,
      song_count: 380,
      platform_count: 4,
      dominant_genre: "pop",
      new_entries: 19,
      ...COORDS.PH,
    },
    {
      country_code: "ID",
      country_name: "Indonesia",
      activity_score: 0.52,
      song_count: 340,
      platform_count: 4,
      dominant_genre: "pop",
      new_entries: 16,
      ...COORDS.ID,
    },
    {
      country_code: "EG",
      country_name: "Egypt",
      activity_score: 0.4,
      song_count: 150,
      platform_count: 3,
      dominant_genre: "pop",
      new_entries: 8,
      ...COORDS.EG,
    },
    {
      country_code: "TR",
      country_name: "Turkey",
      activity_score: 0.54,
      song_count: 360,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 17,
      ...COORDS.TR,
    },
    {
      country_code: "SE",
      country_name: "Sweden",
      activity_score: 0.6,
      song_count: 420,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 18,
      ...COORDS.SE,
    },
    {
      country_code: "ES",
      country_name: "Spain",
      activity_score: 0.69,
      song_count: 750,
      platform_count: 6,
      dominant_genre: "latin",
      new_entries: 33,
      ...COORDS.ES,
    },
    {
      country_code: "IT",
      country_name: "Italy",
      activity_score: 0.58,
      song_count: 440,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 20,
      ...COORDS.IT,
    },
    {
      country_code: "CA",
      country_name: "Canada",
      activity_score: 0.78,
      song_count: 1100,
      platform_count: 6,
      dominant_genre: "hip hop",
      new_entries: 48,
      ...COORDS.CA,
    },
    {
      country_code: "NL",
      country_name: "Netherlands",
      activity_score: 0.56,
      song_count: 390,
      platform_count: 5,
      dominant_genre: "electronic",
      new_entries: 16,
      ...COORDS.NL,
    },
    {
      country_code: "PL",
      country_name: "Poland",
      activity_score: 0.44,
      song_count: 230,
      platform_count: 4,
      dominant_genre: "hip hop",
      new_entries: 11,
      ...COORDS.PL,
    },
    {
      country_code: "TH",
      country_name: "Thailand",
      activity_score: 0.47,
      song_count: 260,
      platform_count: 4,
      dominant_genre: "k-pop",
      new_entries: 13,
      ...COORDS.TH,
    },
    {
      country_code: "VN",
      country_name: "Vietnam",
      activity_score: 0.38,
      song_count: 140,
      platform_count: 3,
      dominant_genre: "pop",
      new_entries: 7,
      ...COORDS.VN,
    },
    {
      country_code: "CL",
      country_name: "Chile",
      activity_score: 0.53,
      song_count: 350,
      platform_count: 5,
      dominant_genre: "latin",
      new_entries: 15,
      ...COORDS.CL,
    },
    {
      country_code: "PE",
      country_name: "Peru",
      activity_score: 0.49,
      song_count: 280,
      platform_count: 4,
      dominant_genre: "latin",
      new_entries: 13,
      ...COORDS.PE,
    },
    {
      country_code: "MA",
      country_name: "Morocco",
      activity_score: 0.35,
      song_count: 120,
      platform_count: 3,
      dominant_genre: "hip hop",
      new_entries: 6,
      ...COORDS.MA,
    },
    {
      country_code: "SA",
      country_name: "Saudi Arabia",
      activity_score: 0.42,
      song_count: 190,
      platform_count: 4,
      dominant_genre: "pop",
      new_entries: 9,
      ...COORDS.SA,
    },
    {
      country_code: "AE",
      country_name: "UAE",
      activity_score: 0.39,
      song_count: 160,
      platform_count: 4,
      dominant_genre: "hip hop",
      new_entries: 8,
      ...COORDS.AE,
    },
    {
      country_code: "IL",
      country_name: "Israel",
      activity_score: 0.36,
      song_count: 130,
      platform_count: 3,
      dominant_genre: "pop",
      new_entries: 5,
      ...COORDS.IL,
    },
    {
      country_code: "RO",
      country_name: "Romania",
      activity_score: 0.34,
      song_count: 110,
      platform_count: 3,
      dominant_genre: "electronic",
      new_entries: 5,
      ...COORDS.RO,
    },
    {
      country_code: "PT",
      country_name: "Portugal",
      activity_score: 0.43,
      song_count: 200,
      platform_count: 4,
      dominant_genre: "latin",
      new_entries: 9,
      ...COORDS.PT,
    },
    {
      country_code: "NO",
      country_name: "Norway",
      activity_score: 0.5,
      song_count: 300,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 12,
      ...COORDS.NO,
    },
    {
      country_code: "DK",
      country_name: "Denmark",
      activity_score: 0.46,
      song_count: 250,
      platform_count: 4,
      dominant_genre: "pop",
      new_entries: 10,
      ...COORDS.DK,
    },
    {
      country_code: "FI",
      country_name: "Finland",
      activity_score: 0.41,
      song_count: 170,
      platform_count: 4,
      dominant_genre: "electronic",
      new_entries: 7,
      ...COORDS.FI,
    },
    {
      country_code: "IE",
      country_name: "Ireland",
      activity_score: 0.51,
      song_count: 320,
      platform_count: 5,
      dominant_genre: "pop",
      new_entries: 14,
      ...COORDS.IE,
    },
    {
      country_code: "NZ",
      country_name: "New Zealand",
      activity_score: 0.37,
      song_count: 130,
      platform_count: 4,
      dominant_genre: "pop",
      new_entries: 6,
      ...COORDS.NZ,
    },
    {
      country_code: "SG",
      country_name: "Singapore",
      activity_score: 0.44,
      song_count: 220,
      platform_count: 4,
      dominant_genre: "k-pop",
      new_entries: 10,
      ...COORDS.SG,
    },
    {
      country_code: "MY",
      country_name: "Malaysia",
      activity_score: 0.4,
      song_count: 170,
      platform_count: 3,
      dominant_genre: "k-pop",
      new_entries: 8,
      ...COORDS.MY,
    },
    {
      country_code: "TZ",
      country_name: "Tanzania",
      activity_score: 0.32,
      song_count: 90,
      platform_count: 3,
      dominant_genre: "afrobeats",
      new_entries: 5,
      ...COORDS.TZ,
    },
    {
      country_code: "SN",
      country_name: "Senegal",
      activity_score: 0.28,
      song_count: 70,
      platform_count: 2,
      dominant_genre: "afrobeats",
      new_entries: 4,
      ...COORDS.SN,
    },
    {
      country_code: "CI",
      country_name: "Ivory Coast",
      activity_score: 0.3,
      song_count: 80,
      platform_count: 2,
      dominant_genre: "afrobeats",
      new_entries: 4,
      ...COORDS.CI,
    },
    {
      country_code: "UA",
      country_name: "Ukraine",
      activity_score: 0.38,
      song_count: 140,
      platform_count: 3,
      dominant_genre: "electronic",
      new_entries: 6,
      ...COORDS.UA,
    },
  ] as Omit<GlobeCountry, "raw_activity" | "label_songs">[]
).map((c) => ({
  ...c,
  raw_activity: c.song_count,
  label_songs: Math.round(c.song_count * 0.03),
}));

/* ─── Mock flow arcs ──────────────────────────────────────────── */

const mockFlows: FlowArc[] = [
  {
    id: "f1",
    song_name: "L2B",
    artist_name: "Central Cee",
    genre: "hip hop",
    velocity: 0.92,
    path: [
      { country_code: "GB", date: "2026-03-25" },
      { country_code: "US", date: "2026-03-28" },
      { country_code: "DE", date: "2026-03-30" },
      { country_code: "FR", date: "2026-04-01" },
    ],
  },
  {
    id: "f2",
    song_name: "Monaco",
    artist_name: "Bad Bunny",
    genre: "latin",
    velocity: 0.88,
    path: [
      { country_code: "MX", date: "2026-03-22" },
      { country_code: "CO", date: "2026-03-24" },
      { country_code: "ES", date: "2026-03-26" },
      { country_code: "US", date: "2026-03-28" },
      { country_code: "AR", date: "2026-03-30" },
    ],
  },
  {
    id: "f3",
    song_name: "Last Last (Remix)",
    artist_name: "Burna Boy ft. Tems",
    genre: "afrobeats",
    velocity: 0.85,
    path: [
      { country_code: "NG", date: "2026-03-20" },
      { country_code: "GH", date: "2026-03-22" },
      { country_code: "GB", date: "2026-03-25" },
      { country_code: "US", date: "2026-03-29" },
    ],
  },
  {
    id: "f4",
    song_name: "Magnetic",
    artist_name: "ILLIT",
    genre: "k-pop",
    velocity: 0.9,
    path: [
      { country_code: "KR", date: "2026-03-18" },
      { country_code: "JP", date: "2026-03-20" },
      { country_code: "PH", date: "2026-03-23" },
      { country_code: "TH", date: "2026-03-25" },
      { country_code: "US", date: "2026-03-28" },
    ],
  },
  {
    id: "f5",
    song_name: "Cruel Summer",
    artist_name: "Taylor Swift",
    genre: "pop",
    velocity: 0.75,
    path: [
      { country_code: "US", date: "2026-03-15" },
      { country_code: "GB", date: "2026-03-17" },
      { country_code: "AU", date: "2026-03-19" },
      { country_code: "CA", date: "2026-03-20" },
    ],
  },
  {
    id: "f6",
    song_name: "Midnight Runner",
    artist_name: "ODESZA",
    genre: "electronic",
    velocity: 0.72,
    path: [
      { country_code: "US", date: "2026-03-21" },
      { country_code: "DE", date: "2026-03-24" },
      { country_code: "NL", date: "2026-03-26" },
      { country_code: "SE", date: "2026-03-28" },
    ],
  },
  {
    id: "f7",
    song_name: "Southside",
    artist_name: "Lil Nas X",
    genre: "hip hop",
    velocity: 0.82,
    path: [
      { country_code: "US", date: "2026-03-20" },
      { country_code: "CA", date: "2026-03-22" },
      { country_code: "GB", date: "2026-03-24" },
      { country_code: "NG", date: "2026-03-27" },
    ],
  },
  {
    id: "f8",
    song_name: "Caliente",
    artist_name: "Rauw Alejandro",
    genre: "latin",
    velocity: 0.8,
    path: [
      { country_code: "CO", date: "2026-03-19" },
      { country_code: "MX", date: "2026-03-21" },
      { country_code: "CL", date: "2026-03-24" },
      { country_code: "US", date: "2026-03-27" },
    ],
  },
  {
    id: "f9",
    song_name: "Essence Pt. 2",
    artist_name: "Wizkid",
    genre: "afrobeats",
    velocity: 0.78,
    path: [
      { country_code: "NG", date: "2026-03-22" },
      { country_code: "KE", date: "2026-03-24" },
      { country_code: "ZA", date: "2026-03-26" },
      { country_code: "GB", date: "2026-03-29" },
    ],
  },
  {
    id: "f10",
    song_name: "Save Me",
    artist_name: "Joji",
    genre: "r&b",
    velocity: 0.7,
    path: [
      { country_code: "JP", date: "2026-03-18" },
      { country_code: "US", date: "2026-03-21" },
      { country_code: "AU", date: "2026-03-24" },
    ],
  },
  {
    id: "f11",
    song_name: "Texas Sun",
    artist_name: "Leon Bridges",
    genre: "country",
    velocity: 0.65,
    path: [
      { country_code: "US", date: "2026-03-20" },
      { country_code: "CA", date: "2026-03-23" },
      { country_code: "AU", date: "2026-03-26" },
    ],
  },
  {
    id: "f12",
    song_name: "Talk Too Much",
    artist_name: "Rema",
    genre: "afrobeats",
    velocity: 0.86,
    path: [
      { country_code: "NG", date: "2026-03-23" },
      { country_code: "GH", date: "2026-03-25" },
      { country_code: "KE", date: "2026-03-27" },
      { country_code: "GB", date: "2026-03-30" },
      { country_code: "US", date: "2026-04-02" },
    ],
  },
];

/* ─── Mock alerts ─────────────────────────────────────────────── */

const mockAlerts: GlobeAlert[] = [
  {
    id: "a1",
    type: "surge",
    message: "L2B surging on 3 platforms (Shazam +233%)",
    artist_name: "Central Cee",
    song_name: "L2B",
  },
  {
    id: "a2",
    type: "domination",
    message: "Bad Bunny dominating 12 markets across Latin America",
    artist_name: "Bad Bunny",
  },
  {
    id: "a3",
    type: "new_entry",
    message: "Talk Too Much entered TikTok Nigeria at #19",
    artist_name: "Rema",
    song_name: "Talk Too Much",
    country_code: "NG",
  },
  {
    id: "a4",
    type: "breakout",
    message: "ILLIT Magnetic spreading to 5 SEA markets in 7 days",
    artist_name: "ILLIT",
    song_name: "Magnetic",
  },
  {
    id: "a5",
    type: "surge",
    message: "Burna Boy Last Last (Remix) +180% Shazam UK in 48 hours",
    artist_name: "Burna Boy",
    song_name: "Last Last (Remix)",
  },
  {
    id: "a6",
    type: "new_entry",
    message: "ODESZA Midnight Runner entered Spotify Germany at #42",
    artist_name: "ODESZA",
    song_name: "Midnight Runner",
    country_code: "DE",
  },
  {
    id: "a7",
    type: "domination",
    message: "K-pop commands 68% of Thailand TikTok top 50",
    country_code: "TH",
  },
  {
    id: "a8",
    type: "breakout",
    message: "Rauw Alejandro Caliente crossed 10M streams in 5 days",
    artist_name: "Rauw Alejandro",
    song_name: "Caliente",
  },
];

/* ─── Assembled mock globe data ───────────────────────────────── */

export const MOCK_GLOBE_DATA: GlobeData = {
  countries: mockCountries,
  flows: mockFlows,
  counters: {
    total_songs: 13757,
    total_countries: 152,
    total_platforms: 7,
    total_observations: 58573,
    total_artists: 37938,
  },
  alerts: mockAlerts,
};

/* ─── Mock country detail (Nigeria example) ───────────────────── */

export const MOCK_COUNTRY_DETAIL: Record<string, CountryDetailData> = {
  NG: {
    country_code: "NG",
    country_name: "Nigeria",
    song_count: 372,
    platform_count: 6,
    trending_up: 42,
    new_entries: 23,
    songs: [
      {
        entity_id: "mock-ng-1",
        song_name: "Talk Too Much",
        artist_name: "Rema",
        is_label_roster: true,
        velocity_class: "accelerating",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 5,
            rank_change: "NEW",
            is_new: true,
          },
          {
            platform: "Spotify",
            metric: "chart_position",
            rank: 12,
            rank_change: "+8",
            is_new: false,
          },
        ],
        also_in: ["GB", "KE", "GH"],
      },
      {
        entity_id: "mock-ng-2",
        song_name: "Last Last (Remix)",
        artist_name: "Burna Boy ft. Tems",
        is_label_roster: true,
        velocity_class: "growing",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 3,
            rank_change: "+8",
            is_new: false,
          },
          {
            platform: "Spotify",
            metric: "chart_position",
            rank: 7,
            rank_change: "+3",
            is_new: false,
          },
          {
            platform: "Shazam",
            metric: "chart_position",
            rank: 15,
            rank_change: "NEW",
            is_new: true,
          },
        ],
        also_in: ["GH", "GB", "US"],
      },
      {
        entity_id: "mock-ng-3",
        song_name: "Essence Pt. 2",
        artist_name: "Wizkid",
        is_label_roster: false,
        velocity_class: "growing",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 8,
            rank_change: "+5",
            is_new: false,
          },
          {
            platform: "Spotify",
            metric: "chart_position",
            rank: 22,
            rank_change: "-3",
            is_new: false,
          },
        ],
        also_in: ["KE", "ZA", "GB"],
      },
      {
        entity_id: "mock-ng-4",
        song_name: "Soso",
        artist_name: "Omah Lay",
        is_label_roster: false,
        velocity_class: "new",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 19,
            rank_change: "NEW",
            is_new: true,
          },
        ],
        also_in: ["GH"],
      },
      {
        entity_id: "mock-ng-5",
        song_name: "Rush",
        artist_name: "Ayra Starr",
        is_label_roster: false,
        velocity_class: "steady",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 14,
            rank_change: "-2",
            is_new: false,
          },
          {
            platform: "Spotify",
            metric: "chart_position",
            rank: 35,
            rank_change: "-5",
            is_new: false,
          },
          {
            platform: "YouTube",
            metric: "chart_position",
            rank: 28,
            rank_change: null,
            is_new: false,
          },
        ],
        also_in: ["GH", "KE", "ZA", "GB"],
      },
      {
        entity_id: "mock-ng-6",
        song_name: "Unavailable",
        artist_name: "Davido ft. Musa Keys",
        is_label_roster: false,
        velocity_class: "declining",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 42,
            rank_change: "-12",
            is_new: false,
          },
          {
            platform: "Spotify",
            metric: "chart_position",
            rank: 88,
            rank_change: "-20",
            is_new: false,
          },
        ],
        also_in: ["ZA"],
      },
    ],
    genre_breakdown: [
      { genre: "Afrobeats", count: 168 },
      { genre: "Hip Hop", count: 74 },
      { genre: "Pop", count: 56 },
      { genre: "R&B", count: 37 },
      { genre: "Gospel", count: 22 },
      { genre: "Electronic", count: 15 },
    ],
    platform_breakdown: [
      { platform: "TikTok", count: 325 },
      { platform: "Spotify", count: 200 },
      { platform: "YouTube", count: 150 },
      { platform: "Apple Music", count: 120 },
      { platform: "Shazam", count: 88 },
      { platform: "Audiomack", count: 65 },
    ],
  },
};

/** Get country detail — returns mock data or a generated stub */
export function getMockCountryDetail(countryCode: string): CountryDetailData {
  if (MOCK_COUNTRY_DETAIL[countryCode]) return MOCK_COUNTRY_DETAIL[countryCode];

  const country = mockCountries.find((c) => c.country_code === countryCode);
  const name = country?.country_name ?? countryCode;
  const songCount = country?.song_count ?? 50;

  return {
    country_code: countryCode,
    country_name: name,
    song_count: songCount,
    platform_count: country?.platform_count ?? 3,
    trending_up: Math.round(songCount * 0.12),
    new_entries: country?.new_entries ?? 3,
    songs: [
      {
        entity_id: `mock-${countryCode}-1`,
        song_name: "Sample Track",
        artist_name: "Various Artists",
        is_label_roster: false,
        velocity_class: "steady",
        platforms: [
          {
            platform: "TikTok",
            metric: "chart_position",
            rank: 25,
            rank_change: null,
            is_new: false,
          },
        ],
        also_in: [],
      },
    ],
    genre_breakdown: [
      {
        genre: country?.dominant_genre ?? "Pop",
        count: Math.round(songCount * 0.45),
      },
      { genre: "Hip Hop", count: Math.round(songCount * 0.25) },
      { genre: "Pop", count: Math.round(songCount * 0.15) },
      { genre: "Electronic", count: Math.round(songCount * 0.15) },
    ],
    platform_breakdown: [
      { platform: "TikTok", count: Math.round(songCount * 0.85) },
      { platform: "Spotify", count: Math.round(songCount * 0.55) },
      { platform: "YouTube", count: Math.round(songCount * 0.4) },
    ],
  };
}
