/** Genre → color mapping for globe visualization */
export const GENRE_COLORS: Record<string, string> = {
  "hip hop": "#8B5CF6",
  pop: "#EC4899",
  latin: "#F97316",
  afrobeats: "#14B8A6",
  "k-pop": "#3B82F6",
  country: "#EAB308",
  rock: "#EF4444",
  "r&b": "#A855F7",
  electronic: "#06B6D4",
  reggaeton: "#F59E0B",
  indie: "#10B981",
};

const DEFAULT_COLOR = "#6B7280";

export function genreColor(genre: string): string {
  return GENRE_COLORS[genre.toLowerCase()] ?? DEFAULT_COLOR;
}

/** Velocity class → color */
export const VELOCITY_COLORS: Record<string, string> = {
  accelerating: "#22C55E",
  growing: "#3B82F6",
  new: "#A855F7",
  steady: "#6B7280",
  declining: "#EF4444",
  decelerating: "#F97316",
};

/** Alert type → icon */
export const ALERT_ICONS: Record<string, string> = {
  surge: "",
  new_entry: "",
  domination: "",
  breakout: "",
};

/* ─── Arbitrage / Radar colors ─────────────────────────────── */

export const ARBITRAGE_COLORS = {
  HIGH: "#22C55E",
  MEDIUM: "#EAB308",
  LOW: "#6B7280",
} as const;

/** ROI multiplier → color for the hero "×" number */
export function roiColor(roi: number): string {
  if (roi > 3) return "#22C55E";
  if (roi > 2) return "#4ADE80";
  if (roi > 1.5) return "#EAB308";
  if (roi > 1) return "#F97316";
  return "#EF4444";
}

/** ISO alpha-3 → alpha-2 lookup for world-atlas matching */
export const ISO3_TO_ISO2: Record<string, string> = {
  USA: "US",
  GBR: "GB",
  NGA: "NG",
  BRA: "BR",
  MEX: "MX",
  DEU: "DE",
  FRA: "FR",
  JPN: "JP",
  KOR: "KR",
  IND: "IN",
  ZAF: "ZA",
  AUS: "AU",
  COL: "CO",
  ARG: "AR",
  KEN: "KE",
  GHA: "GH",
  PHL: "PH",
  IDN: "ID",
  EGY: "EG",
  TUR: "TR",
  SWE: "SE",
  ESP: "ES",
  ITA: "IT",
  CAN: "CA",
  NLD: "NL",
  POL: "PL",
  THA: "TH",
  VNM: "VN",
  CHL: "CL",
  PER: "PE",
  MAR: "MA",
  SAU: "SA",
  ARE: "AE",
  ISR: "IL",
  ROU: "RO",
  UKR: "UA",
  PRT: "PT",
  NOR: "NO",
  DNK: "DK",
  FIN: "FI",
  IRL: "IE",
  NZL: "NZ",
  SGP: "SG",
  MYS: "MY",
  TZA: "TZ",
  SEN: "SN",
  CIV: "CI",
  // Extended set for world-atlas coverage
  CHN: "CN",
  RUS: "RU",
  PAK: "PK",
  BGD: "BD",
  ETH: "ET",
  COD: "CD",
  MMR: "MM",
  IRN: "IR",
  AGO: "AO",
  MOZ: "MZ",
  MDG: "MG",
  CMR: "CM",
  NER: "NE",
  BFA: "BF",
  MLI: "ML",
  MWI: "MW",
  ZMB: "ZM",
  TCD: "TD",
  SOM: "SO",
  ZWE: "ZW",
  GIN: "GN",
  RWA: "RW",
  BEN: "BJ",
  TUN: "TN",
  BOL: "BO",
  HTI: "HT",
  DOM: "DO",
  CUB: "CU",
  GTM: "GT",
  ECU: "EC",
  HND: "HN",
  PRY: "PY",
  SLV: "SV",
  NIC: "NI",
  CRI: "CR",
  PAN: "PA",
  URY: "UY",
  JAM: "JM",
  TTO: "TT",
  GUY: "GY",
  SUR: "SR",
  BLZ: "BZ",
  BHS: "BS",
  IRQ: "IQ",
  AFG: "AF",
  NPL: "NP",
  LKA: "LK",
  KHM: "KH",
  LAO: "LA",
  MNG: "MN",
  TWN: "TW",
  HKG: "HK",
  BRN: "BN",
  TLS: "TL",
  PNG: "PG",
  FJI: "FJ",
  SLB: "SB",
  VUT: "VU",
  WSM: "WS",
  BTN: "BT",
  QAT: "QA",
  KWT: "KW",
  OMN: "OM",
  BHR: "BH",
  JOR: "JO",
  LBN: "LB",
  SYR: "SY",
  YEM: "YE",
  GEO: "GE",
  ARM: "AM",
  AZE: "AZ",
  UZB: "UZ",
  TKM: "TM",
  KAZ: "KZ",
  KGZ: "KG",
  TJK: "TJ",
  BLR: "BY",
  MDA: "MD",
  LTU: "LT",
  LVA: "LV",
  EST: "EE",
  HRV: "HR",
  SVN: "SI",
  SVK: "SK",
  CZE: "CZ",
  HUN: "HU",
  BGR: "BG",
  SRB: "RS",
  BIH: "BA",
  MNE: "ME",
  MKD: "MK",
  ALB: "AL",
  GRC: "GR",
  CHE: "CH",
  AUT: "AT",
  BEL: "BE",
  LUX: "LU",
  ISL: "IS",
  CYP: "CY",
  MLT: "MT",
  LBY: "LY",
  SDN: "SD",
  SSD: "SS",
  ERI: "ER",
  DJI: "DJ",
  UGA: "UG",
  GAB: "GA",
  GNQ: "GQ",
  COG: "CG",
  CAF: "CF",
  NAM: "NA",
  BWA: "BW",
  LSO: "LS",
  SWZ: "SZ",
  MRT: "MR",
  GMB: "GM",
  GNB: "GW",
  SLE: "SL",
  LBR: "LR",
  TGO: "TG",
  CPV: "CV",
  STP: "ST",
  COM: "KM",
  MUS: "MU",
  SYC: "SC",
};

/** Numeric UN M49 code → ISO alpha-2 (for world-atlas 110m which uses numeric IDs) */
export const NUMERIC_TO_ISO2: Record<string, string> = {
  "840": "US",
  "826": "GB",
  "566": "NG",
  "076": "BR",
  "484": "MX",
  "276": "DE",
  "250": "FR",
  "392": "JP",
  "410": "KR",
  "356": "IN",
  "710": "ZA",
  "036": "AU",
  "170": "CO",
  "032": "AR",
  "404": "KE",
  "288": "GH",
  "608": "PH",
  "360": "ID",
  "818": "EG",
  "792": "TR",
  "752": "SE",
  "724": "ES",
  "380": "IT",
  "124": "CA",
  "528": "NL",
  "616": "PL",
  "764": "TH",
  "704": "VN",
  "152": "CL",
  "604": "PE",
  "504": "MA",
  "682": "SA",
  "784": "AE",
  "376": "IL",
  "642": "RO",
  "804": "UA",
  "620": "PT",
  "578": "NO",
  "208": "DK",
  "246": "FI",
  "372": "IE",
  "554": "NZ",
  "702": "SG",
  "458": "MY",
  "834": "TZ",
  "686": "SN",
  "384": "CI",
  "156": "CN",
  "643": "RU",
  "586": "PK",
  "050": "BD",
  "231": "ET",
  "180": "CD",
  "104": "MM",
  "364": "IR",
  "024": "AO",
  "508": "MZ",
  "450": "MG",
  "120": "CM",
  "562": "NE",
  "854": "BF",
  "466": "ML",
  "454": "MW",
  "894": "ZM",
  "148": "TD",
  "706": "SO",
  "716": "ZW",
  "324": "GN",
  "646": "RW",
  "204": "BJ",
  "788": "TN",
  "068": "BO",
  "332": "HT",
  "214": "DO",
  "192": "CU",
  "320": "GT",
  "218": "EC",
  "340": "HN",
  "600": "PY",
  "222": "SV",
  "558": "NI",
  "188": "CR",
  "591": "PA",
  "858": "UY",
  "388": "JM",
  "780": "TT",
  "368": "IQ",
  "004": "AF",
  "524": "NP",
  "144": "LK",
  "116": "KH",
  "418": "LA",
  "496": "MN",
  "158": "TW",
  "634": "QA",
  "414": "KW",
  "512": "OM",
  "400": "JO",
  "422": "LB",
  "760": "SY",
  "887": "YE",
  "268": "GE",
  "051": "AM",
  "031": "AZ",
  "860": "UZ",
  "795": "TM",
  "398": "KZ",
  "417": "KG",
  "762": "TJ",
  "112": "BY",
  "498": "MD",
  "440": "LT",
  "428": "LV",
  "233": "EE",
  "191": "HR",
  "705": "SI",
  "703": "SK",
  "203": "CZ",
  "348": "HU",
  "100": "BG",
  "688": "RS",
  "070": "BA",
  "499": "ME",
  "807": "MK",
  "008": "AL",
  "300": "GR",
  "756": "CH",
  "040": "AT",
  "056": "BE",
  "442": "LU",
  "352": "IS",
  "196": "CY",
  "434": "LY",
  "729": "SD",
  "728": "SS",
  "232": "ER",
  "262": "DJ",
  "800": "UG",
  "266": "GA",
  "226": "GQ",
  "178": "CG",
  "140": "CF",
  "516": "NA",
  "072": "BW",
  "426": "LS",
  "748": "SZ",
  "478": "MR",
  "270": "GM",
  "624": "GW",
  "694": "SL",
  "430": "LR",
  "768": "TG",
};
