import { useEffect, useMemo, useState } from "react";
import { AnimatePresence, motion } from "framer-motion";
import {
  ChevronDown,
  FileText,
  Loader2,
  Settings2,
  Upload,
  X,
} from "lucide-react";
import { useSearchParams } from "react-router-dom";
import { supabase } from "@/integrations/supabase/client";
import { useUserProfile } from "@/contexts/UserProfileContext";
import { useLabelArtists } from "@/hooks/useLabelArtists";
import { toast } from "@/hooks/use-toast";
import type { Angle, OutputType, QueueItem } from "./types";
import {
  ANGLE_FAMILY_COLOR,
  ANGLE_FAMILY_LABEL,
  MOCK_ARTISTS,
  OUTPUT_TYPE_LABEL,
} from "./mockData";
import CartoonPanel, { type CartoonGenerateInput } from "./CartoonPanel";
import { Button } from "@/components/ui/button";
import { MOCKED_PRESETS, PRESETS } from "./presets";

const SUPABASE_URL = "https://kxvgbowrkmowuyezoeke.supabase.co";

export interface CreateJobInput {
  jobId: string;
  count: number;
  artistHandle: string;
  source: "live_performance" | "podcasts";
}

// Wizard payload for the Lyric Overlay (link_video) pipeline. The handler in
// ContentFactoryV2 owns the placeholder QueueItem + polling reconciler;
// CreateView just forwards the freshly-issued job_id and form context.
export interface LinkVideoJobInput {
  jobId: string;
  artistHandle: string;
  refUrl: string;
  transcribeProvider: "audioshake" | "whisperx";
}

interface CreateViewProps {
  angles: Angle[];
  draftAngleId: string | null;
  draftPreset: OutputType | null;
  onDraftConsumed: () => void;
  onGenerate: (item: QueueItem) => void;
  onCreateJob: (job: CreateJobInput) => void;
  onCartoonGenerate: (input: CartoonGenerateInput) => Promise<void> | void;
  cartoonsInFlight: number;
  onLinkVideoJob: (input: LinkVideoJobInput) => void;
}

const PENDING_FAN_BRIEFS = [
  { id: "fb-1", title: "Maren anxiety routine — fan-submitted v3" },
  { id: "fb-2", title: "Folami voice memos — retake from fan clip" },
  { id: "fb-3", title: "Papi 4am journaling — quote-card request" },
  { id: "fb-4", title: "Gracie phone-demo BTS — fan-stitched v2" },
];

export default function CreateView({
  angles,
  draftAngleId,
  draftPreset,
  onDraftConsumed,
  onGenerate,
  onCreateJob,
  onCartoonGenerate,
  cartoonsInFlight,
  onLinkVideoJob,
}: CreateViewProps) {
  const [activePreset, setActivePreset] = useState<OutputType | null>(null);
  const [selectedArtistId, setSelectedArtistId] = useState<string>("art-papi");
  const [selectedAvatar, setSelectedAvatar] = useState<string>("av-native");
  const [tuneOpen, setTuneOpen] = useState(false);

  // Preset-specific form state (kept simple for mock)
  const [angleId, setAngleId] = useState<string>("");
  const [aspectRatio, setAspectRatio] = useState<"9:16" | "1:1" | "16:9">(
    "9:16",
  );
  const [durationSec, setDurationSec] = useState(30);
  const [musicBed, setMusicBed] = useState<"native" | "original" | "cue_a">(
    "native",
  );
  const [storyStructure, setStoryStructure] = useState<
    "3_act" | "5_chapter" | "chronological" | "investigative"
  >("3_act");
  const [researchDepth, setResearchDepth] = useState<
    "Light" | "Deep" | "Investigative"
  >("Deep");
  const [numAngles, setNumAngles] = useState(3);
  const [narrator, setNarrator] = useState<"artist" | "neutral" | "fan">(
    "neutral",
  );
  const [pacing, setPacing] = useState<"steady" | "cold_open" | "builder">(
    "builder",
  );
  const [toneSlider, setToneSlider] = useState(40);
  const [tourHighlight, setTourHighlight] = useState<
    "crowd" | "setlist" | "bts"
  >("crowd");
  const [fanBriefId, setFanBriefId] = useState<string>("");
  const [fanBriefEdit, setFanBriefEdit] = useState<string>("");

  // Lyric Overlay (link_video) preset: real fields porting the legacy
  // /label/content-factory form. `linkUrl` is the TikTok ref,
  // `linkArtistHandle` is free-text (legacy had it free-text too — handle is
  // used for slugified file paths + display titles, not as a roster join key,
  // so an unknown artist still works).
  const [linkUrl, setLinkUrl] = useState<string>("");
  const [linkArtistHandle, setLinkArtistHandle] = useState<string>("");
  const [linkMp3File, setLinkMp3File] = useState<File | null>(null);
  const [linkTranscribeProvider, setLinkTranscribeProvider] = useState<
    "audioshake" | "whisperx"
  >("audioshake");
  const [linkSubmitting, setLinkSubmitting] = useState(false);
  const [linkErrMsg, setLinkErrMsg] = useState<string | null>(null);
  const [linkUserId, setLinkUserId] = useState<string | null>(null);

  // Cross-format AI script model preference. Applies to every Content Factory
  // format whose script is generated by the chat agent (cartoon, real-footage,
  // future formats). Persisted in localStorage so the choice survives reloads.
  // The Tune drawer renders the dropdown; handleCartoonGenerate (in the parent)
  // reads the same key at dispatch time, so no prop drilling is needed.
  const [scriptModel, setScriptModel] = useState<
    "claude-opus-4-7" | "claude-sonnet-4-6" | "gpt-5.5"
  >(() => {
    try {
      const saved = window.localStorage.getItem("wavebound_cf_script_model");
      if (
        saved === "claude-opus-4-7" ||
        saved === "claude-sonnet-4-6" ||
        saved === "gpt-5.5"
      )
        return saved;
    } catch {
      /* localStorage disabled */
    }
    return "claude-opus-4-7";
  });
  useEffect(() => {
    try {
      window.localStorage.setItem("wavebound_cf_script_model", scriptModel);
    } catch {
      /* localStorage disabled */
    }
  }, [scriptModel]);

  // Fan-brief wizard state. The wizard is single-phase now: pick artist +
  // source + count, hit Create, items go straight to Review. Initial values
  // seed from URL params so refresh preserves selection.
  const [searchParams, setSearchParams] = useSearchParams();
  const [briefArtistHandle, setBriefArtistHandle] = useState<string>(
    () => searchParams.get("fbArtist") ?? "",
  );
  const [briefSource, setBriefSource] = useState<
    "live_performance" | "podcasts" | ""
  >(() => {
    const v = searchParams.get("fbSource");
    return v === "live_performance" || v === "podcasts" ? v : "";
  });
  const [briefCount, setBriefCount] = useState<number>(() => {
    const v = Number(searchParams.get("fbCount"));
    return Number.isFinite(v) && v >= 1 && v <= 20 ? v : 5;
  });
  const [isCreating, setIsCreating] = useState(false);

  const { labelId } = useUserProfile();

  // Label roster — populates the wizard's artist dropdown. The hook returns
  // every roster row; we drop ones without a handle (the wizard joins fan-
  // brief generation on handle so a null one can't be selected).
  const labelArtistsQuery = useLabelArtists(labelId);
  const labelArtists = (labelArtistsQuery.data ?? []).filter(
    (a) => !!a.artist_handle,
  );

  // Trigger a fresh on-demand pipeline run via the backend edge function.
  // Fire-and-forget: endpoint returns { jobId, status: 'queued' } in <1s, the
  // worker picks it up within 60s, and Realtime updates land in Review as the
  // pipeline progresses. The wizard hands the jobId off to the parent which
  // owns queue placeholders + reconciliation.
  const handleCreate = async () => {
    if (!briefArtistHandle || !briefSource || !labelId || isCreating) return;
    setIsCreating(true);

    console.log("[fan-brief-wizard] create", {
      artist: briefArtistHandle,
      source: briefSource,
      count: briefCount,
      labelId,
    });

    // POST with 15s abort timeout + one transparent retry on 401 after
    // refreshing the session. Network throw / explicit abort flow into the
    // same toast path; finally always re-enables the button.
    const POST_TIMEOUT_MS = 15_000;

    const postOnce = async (
      accessToken: string,
    ): Promise<{ res: Response; body: { error?: string; jobId?: string } }> => {
      const ctrl = new AbortController();
      const timer = window.setTimeout(() => ctrl.abort(), POST_TIMEOUT_MS);
      try {
        const res = await fetch(
          `${SUPABASE_URL}/functions/v1/fan-briefs-generate-on-demand`,
          {
            method: "POST",
            headers: {
              Authorization: `Bearer ${accessToken}`,
              "Content-Type": "application/json",
              apikey: import.meta.env.VITE_SUPABASE_ANON_KEY ?? "",
            },
            body: JSON.stringify({
              labelId,
              artistHandle: briefArtistHandle,
              source: briefSource,
              count: briefCount,
            }),
            signal: ctrl.signal,
          },
        );
        const body = (await res.json().catch(() => ({}))) as {
          error?: string;
          jobId?: string;
        };
        return { res, body };
      } finally {
        window.clearTimeout(timer);
      }
    };

    try {
      const session = (await supabase.auth.getSession()).data.session;
      if (!session) {
        toast({
          title: "Session expired",
          description: "Please refresh and sign in again.",
          variant: "destructive",
        });
        return;
      }

      let { res, body } = await postOnce(session.access_token);

      // 401: token may have expired between getSession() and the POST. Try
      // a single refresh + retry before surfacing failure to the user.
      if (res.status === 401) {
        console.warn(
          "[fan-brief-wizard] 401 — refreshing session and retrying",
        );
        const refreshed = await supabase.auth.refreshSession();
        const newToken = refreshed.data.session?.access_token;
        if (!newToken) {
          toast({
            title: "Session expired",
            description: "Please log out and back in.",
            variant: "destructive",
          });
          return;
        }
        ({ res, body } = await postOnce(newToken));
      }

      if (!res.ok) {
        const description =
          body?.error ||
          (res.status === 401
            ? "Session expired — please log out and back in."
            : res.status === 429
              ? "Already running for this artist + source. Wait a minute and retry."
              : res.status === 403
                ? "You don't have access to this label."
                : `Request failed (${res.status}).`);
        toast({
          title: "Create failed",
          description,
          variant: "destructive",
        });
        return;
      }

      const jobId = body?.jobId;
      if (!jobId) {
        toast({
          title: "Create failed",
          description: "Backend did not return a jobId.",
          variant: "destructive",
        });
        return;
      }

      onCreateJob({
        jobId,
        count: briefCount,
        artistHandle: briefArtistHandle,
        source: briefSource,
      });

      // Reset wizard + URL so the next batch starts fresh.
      setBriefArtistHandle("");
      setBriefSource("");
      setBriefCount(5);
      setSearchParams(
        (prev) => {
          const next = new URLSearchParams(prev);
          next.delete("fbArtist");
          next.delete("fbSource");
          next.delete("fbCount");
          return next;
        },
        { replace: true },
      );
    } catch (err) {
      const aborted = err instanceof DOMException && err.name === "AbortError";
      toast({
        title: "Create failed",
        description: aborted
          ? "Couldn't reach the briefs service in 15s — check your connection and try again."
          : err instanceof Error
            ? err.message
            : "Network error",
        variant: "destructive",
      });
    } finally {
      setIsCreating(false);
    }
  };

  // Hydrate from a draft (when user hits "Send to Create" in Angles)
  useEffect(() => {
    if (!draftAngleId && !draftPreset) return;
    if (draftPreset) setActivePreset(draftPreset);
    if (draftAngleId) {
      const angle = angles.find((a) => a.id === draftAngleId);
      if (angle) {
        setSelectedArtistId(angle.artistId);
        setAngleId(angle.id);
      }
    }
    onDraftConsumed();
  }, [draftAngleId, draftPreset, angles, onDraftConsumed]);

  // Sync wizard state → URL params so refresh preserves selection and a
  // copied URL lands somebody else with the same picks (once they re-enter
  // the preset). Defaults are dropped so the URL stays clean.
  useEffect(() => {
    if (activePreset !== "fan_brief") return;
    setSearchParams(
      (prev) => {
        const next = new URLSearchParams(prev);
        if (briefArtistHandle) next.set("fbArtist", briefArtistHandle);
        else next.delete("fbArtist");
        if (briefSource) next.set("fbSource", briefSource);
        else next.delete("fbSource");
        if (briefCount !== 5) next.set("fbCount", String(briefCount));
        else next.delete("fbCount");
        return next;
      },
      { replace: true },
    );
  }, [
    activePreset,
    briefArtistHandle,
    briefSource,
    briefCount,
    setSearchParams,
  ]);

  const selectedAngle = angleId
    ? angles.find((a) => a.id === angleId)
    : undefined;

  const availableAngles = useMemo(
    () => angles.filter((a) => a.artistId === selectedArtistId && !a.killed),
    [angles, selectedArtistId],
  );

  const selectedArtist = MOCK_ARTISTS.find((a) => a.id === selectedArtistId);

  // Read user id once for the transcribe-provider localStorage key. We don't
  // gate the form on this — defaults to 'audioshake' until the auth call
  // resolves, then any user-pinned override hydrates in.
  useEffect(() => {
    let cancelled = false;
    void supabase.auth.getUser().then(({ data }) => {
      if (cancelled) return;
      const uid = data.user?.id ?? null;
      setLinkUserId(uid);
      if (!uid) return;
      try {
        const stored = window.localStorage.getItem(
          `cf:transcribe_provider:${uid}`,
        );
        if (stored === "audioshake" || stored === "whisperx") {
          setLinkTranscribeProvider(stored);
        }
      } catch {
        /* localStorage disabled — fine */
      }
    });
    return () => {
      cancelled = true;
    };
  }, []);

  // Persist transcribe-provider preference per user, mirroring the legacy
  // /label/content-factory behavior so the choice carries across sessions.
  useEffect(() => {
    if (!linkUserId) return;
    try {
      window.localStorage.setItem(
        `cf:transcribe_provider:${linkUserId}`,
        linkTranscribeProvider,
      );
    } catch {
      /* localStorage disabled — fine */
    }
  }, [linkUserId, linkTranscribeProvider]);

  // Submit the legacy content-factory pipeline: optional MP3 upload to the
  // 'content-factory' bucket, then invoke('content-factory-generate'). On
  // success the parent owns the placeholder QueueItem + status polling.
  const handleLinkVideoSubmit = async () => {
    if (linkSubmitting) return;
    setLinkErrMsg(null);
    if (!labelId) {
      setLinkErrMsg("No label scope on your profile — contact Paul.");
      return;
    }
    if (!isValidTikTokUrl(linkUrl)) {
      setLinkErrMsg(
        "Reference URL must be a tiktok.com or vm.tiktok.com link.",
      );
      return;
    }
    const handle = stripHandle(linkArtistHandle);
    if (!handle) {
      setLinkErrMsg("Artist handle is required.");
      return;
    }
    if (linkMp3File) {
      if (linkMp3File.size > 10 * 1024 * 1024) {
        setLinkErrMsg(
          `MP3 is ${(linkMp3File.size / 1024 / 1024).toFixed(1)} MB — max 10 MB.`,
        );
        return;
      }
      if (
        !/\.mp3$/i.test(linkMp3File.name) &&
        linkMp3File.type !== "audio/mpeg"
      ) {
        setLinkErrMsg("File must be an MP3.");
        return;
      }
    }

    setLinkSubmitting(true);
    try {
      let artistMp3Path: string | undefined;
      if (linkMp3File) {
        const rand = crypto.randomUUID().slice(0, 8);
        artistMp3Path = `sources/${labelId}/${rand}-${slugifyHandle(handle)}.mp3`;
        const { error: uploadError } = await supabase.storage
          .from("content-factory")
          .upload(artistMp3Path, linkMp3File, {
            contentType: "audio/mpeg",
            upsert: false,
          });
        if (uploadError) throw uploadError;
      }

      const { data, error: invokeError } = await supabase.functions.invoke(
        "content-factory-generate",
        {
          body: {
            label_id: labelId,
            artist_handle: handle,
            ref_tiktok_url: linkUrl.trim(),
            transcribe_provider: linkTranscribeProvider,
            ...(artistMp3Path ? { artist_mp3_path: artistMp3Path } : {}),
          },
        },
      );
      if (invokeError) throw invokeError;
      const returnedJobId =
        (data as { job_id?: string } | null)?.job_id ?? null;
      if (!returnedJobId) {
        throw new Error("No job_id returned from generate endpoint");
      }

      onLinkVideoJob({
        jobId: returnedJobId,
        artistHandle: handle,
        refUrl: linkUrl.trim(),
        transcribeProvider: linkTranscribeProvider,
      });

      // Reset form so the next submit starts fresh.
      setLinkUrl("");
      setLinkArtistHandle("");
      setLinkMp3File(null);
      setActivePreset(null);
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      setLinkErrMsg(msg);
      toast({
        title: "Generation failed",
        description: msg,
        variant: "destructive",
      });
    } finally {
      setLinkSubmitting(false);
    }
  };

  const handleGenerate = () => {
    if (!activePreset || !selectedArtist) return;
    const title = buildMockTitle(
      activePreset,
      selectedArtist.name,
      selectedAngle,
      linkUrl,
    );
    const item: QueueItem = {
      id: `q-gen-${Date.now()}`,
      artistId: selectedArtistId,
      title,
      outputType: activePreset,
      source: activePreset === "fan_brief" ? "fan_brief" : "human",
      status: "pending",
      risk:
        activePreset === "sensational" && selectedAngle?.speculative
          ? "flagged"
          : "low",
      riskNotes:
        activePreset === "sensational" && selectedAngle?.speculative
          ? ["Angle flagged speculative in Angles tab — review sources"]
          : [],
      thumbKind:
        activePreset === "link_video"
          ? "link"
          : activePreset === "fan_brief"
            ? "brief"
            : "video",
      createdAt: "just now",
      angleId: selectedAngle?.id,
    };
    onGenerate(item);
    setActivePreset(null);
    setAngleId("");
    setLinkUrl("");
    setFanBriefEdit("");
    setFanBriefId("");
  };

  return (
    <div
      className="font-['DM_Sans',sans-serif] grid gap-6"
      style={{
        gridTemplateColumns: "minmax(0,1fr) 280px",
        color: "var(--ink)",
      }}
    >
      {/* Main canvas */}
      <div className="flex flex-col gap-6 min-w-0">
        {/* Step 1 — preset cards */}
        <section>
          <SectionHeader
            title="Pick a preset"
            subtitle="Choose what kind of drop you want — fields appear below."
          />
          <motion.div
            className="grid gap-3"
            style={{
              gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
            }}
            variants={{
              hidden: {},
              show: {
                transition: { staggerChildren: 0.04, delayChildren: 0.04 },
              },
            }}
            initial="hidden"
            animate="show"
          >
            {PRESETS.map((p) => {
              const active = activePreset === p.key;
              const isSoon = p.status === "soon";
              return (
                <motion.button
                  key={p.key}
                  type="button"
                  onClick={() => setActivePreset(active ? null : p.key)}
                  variants={{
                    hidden: { opacity: 0, y: 10 },
                    show: {
                      opacity: 1,
                      y: 0,
                      transition: {
                        duration: 0.36,
                        ease: [0.16, 1, 0.3, 1],
                      },
                    },
                  }}
                  className="group relative text-left rounded-2xl overflow-hidden transition-[transform,border-color,box-shadow,background-color,opacity] duration-[var(--dur-state)] ease-[cubic-bezier(0.16,1,0.3,1)] hover:-translate-y-0.5 active:scale-[0.985] active:duration-[var(--dur-instant)]"
                  style={{
                    aspectRatio: "1 / 1",
                    background: active
                      ? "var(--accent-light)"
                      : "var(--surface)",
                    border: `1px solid ${active ? "var(--accent)" : "var(--border)"}`,
                    boxShadow: active
                      ? "0 0 24px rgba(242,93,36,0.25), inset 0 1px 0 rgba(255,255,255,0.04)"
                      : "inset 0 1px 0 rgba(255,255,255,0.04)",
                    opacity: isSoon && !active ? 0.62 : 1,
                  }}
                >
                  {/* Top-right tag */}
                  <div className="absolute top-3 right-3 z-10">
                    {isSoon ? (
                      <span
                        className="px-2 py-0.5 rounded-md text-[9px] font-semibold uppercase tracking-wide"
                        style={{
                          background: "rgba(255,255,255,0.06)",
                          color: "var(--ink-tertiary)",
                          border: "1px solid var(--border)",
                        }}
                      >
                        Soon
                      </span>
                    ) : (
                      <span
                        className="px-2 py-0.5 rounded-md text-[9px] font-semibold uppercase tracking-wide"
                        style={{
                          background: "var(--accent)",
                          color: "#fff",
                        }}
                      >
                        New
                      </span>
                    )}
                  </div>

                  {/* Hover-glow gradient that radiates from icon corner */}
                  <div
                    className="absolute inset-0 opacity-0 group-hover:opacity-100 transition-opacity pointer-events-none"
                    style={{
                      background:
                        "radial-gradient(circle at 18% 22%, rgba(242,93,36,0.12), transparent 60%)",
                    }}
                  />

                  {/* Icon tile top-left */}
                  <div className="absolute top-4 left-4">
                    <div
                      className="w-11 h-11 rounded-xl flex items-center justify-center transition-colors"
                      style={{
                        background: active
                          ? "var(--accent)"
                          : "rgba(255,255,255,0.04)",
                        border: active
                          ? "1px solid var(--accent)"
                          : "1px solid var(--border)",
                      }}
                    >
                      <p.icon
                        size={20}
                        color={active ? "#fff" : "var(--ink)"}
                      />
                    </div>
                  </div>

                  {/* Title + desc bottom-left */}
                  <div className="absolute bottom-4 left-4 right-4 flex flex-col gap-1">
                    <div
                      className="text-[15px] font-semibold leading-tight"
                      style={{ color: "var(--ink)" }}
                    >
                      {p.label}
                    </div>
                    <div
                      className="text-[11.5px] leading-snug line-clamp-2"
                      style={{ color: "var(--ink-tertiary)" }}
                    >
                      {p.description}
                    </div>
                  </div>
                </motion.button>
              );
            })}
          </motion.div>
        </section>

        {/* Step 2 — preset-specific fields. AnimatePresence keyed by
            activePreset so switching presets fades out the old fields and
            slides the new ones up. Open/close uses opacity + translateY
            only (skill rule — no height animation). */}
        <AnimatePresence mode="wait" initial={false}>
          {activePreset && (
            <motion.section
              key={activePreset}
              initial={{ opacity: 0, y: 12 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 8 }}
              transition={{
                duration: 0.36,
                ease: [0.16, 1, 0.3, 1],
              }}
              className="rounded-2xl p-6 flex flex-col gap-5 overflow-hidden"
              style={{
                background: "var(--surface)",
                borderTop: "0.5px solid var(--card-edge)",
              }}
            >
              <div className="flex items-center justify-between gap-3">
                <SectionHeader
                  title={OUTPUT_TYPE_LABEL[activePreset]}
                  subtitle="Only the fields this preset needs."
                  tight
                />
                <button
                  type="button"
                  onClick={() => setActivePreset(null)}
                  className="w-8 h-8 rounded-lg flex items-center justify-center"
                  style={{
                    background: "var(--bg-subtle)",
                    border: "1px solid var(--border)",
                  }}
                  title="Clear preset"
                >
                  <X size={14} color="var(--ink-tertiary)" />
                </button>
              </div>

              {/* Short-form */}
              {activePreset === "short_form" && (
                <>
                  <AnglePicker
                    angles={availableAngles}
                    value={angleId}
                    onChange={setAngleId}
                    allowFreeform
                  />
                  <Row>
                    <Field label="Aspect">
                      <ChipRow
                        options={[
                          { k: "9:16", label: "9:16" },
                          { k: "1:1", label: "1:1" },
                          { k: "16:9", label: "16:9" },
                        ]}
                        value={aspectRatio}
                        onChange={(v) =>
                          setAspectRatio(v as "9:16" | "1:1" | "16:9")
                        }
                      />
                    </Field>
                    <Field label={`Duration — ${durationSec}s`}>
                      <input
                        type="range"
                        min={15}
                        max={60}
                        value={durationSec}
                        onChange={(e) => setDurationSec(Number(e.target.value))}
                        className="w-full"
                        style={{ accentColor: "var(--accent)" }}
                      />
                    </Field>
                  </Row>
                  <Field label="Music bed">
                    <ChipRow
                      options={[
                        { k: "native", label: "Artist track" },
                        { k: "original", label: "Original score" },
                        { k: "cue_a", label: "Cue library A" },
                      ]}
                      value={musicBed}
                      onChange={(v) =>
                        setMusicBed(v as "native" | "original" | "cue_a")
                      }
                    />
                  </Field>
                </>
              )}

              {/* Mini-doc */}
              {activePreset === "mini_doc" && (
                <>
                  <Row>
                    <Field label="Story structure">
                      <Select
                        value={storyStructure}
                        onChange={(v) =>
                          setStoryStructure(
                            v as
                              | "3_act"
                              | "5_chapter"
                              | "chronological"
                              | "investigative",
                          )
                        }
                        options={[
                          { value: "3_act", label: "3-act" },
                          { value: "5_chapter", label: "5-chapter" },
                          { value: "chronological", label: "Chronological" },
                          { value: "investigative", label: "Investigative" },
                        ]}
                      />
                    </Field>
                    <Field label="Research depth">
                      <ChipRow
                        options={[
                          { k: "Light", label: "Light" },
                          { k: "Deep", label: "Deep" },
                          { k: "Investigative", label: "Investigative" },
                        ]}
                        value={researchDepth}
                        onChange={(v) =>
                          setResearchDepth(
                            v as "Light" | "Deep" | "Investigative",
                          )
                        }
                      />
                    </Field>
                  </Row>
                  <AnglePicker
                    angles={availableAngles}
                    value={angleId}
                    onChange={setAngleId}
                    allowFreeform
                    label="Angle source (pick or freeform)"
                  />
                  <Field label={`Number of angles — ${numAngles}`}>
                    <input
                      type="range"
                      min={1}
                      max={6}
                      value={numAngles}
                      onChange={(e) => setNumAngles(Number(e.target.value))}
                      className="w-full"
                      style={{ accentColor: "var(--accent)" }}
                    />
                  </Field>
                </>
              )}

              {/* Sensational */}
              {activePreset === "sensational" && (
                <>
                  <AnglePicker
                    angles={availableAngles.filter(
                      (a) => a.family === "sensational",
                    )}
                    value={angleId}
                    onChange={setAngleId}
                    label="Angle"
                  />
                  <Row>
                    <Field label="Narrator voice">
                      <Select
                        value={narrator}
                        onChange={(v) =>
                          setNarrator(v as "artist" | "neutral" | "fan")
                        }
                        options={[
                          { value: "artist", label: "Artist voice" },
                          { value: "neutral", label: "Neutral editorial" },
                          { value: "fan", label: "Fan narrator" },
                        ]}
                      />
                    </Field>
                    <Field label="Pacing curve">
                      <Select
                        value={pacing}
                        onChange={(v) =>
                          setPacing(v as "steady" | "cold_open" | "builder")
                        }
                        options={[
                          { value: "cold_open", label: "Cold open" },
                          { value: "builder", label: "Builder" },
                          { value: "steady", label: "Steady" },
                        ]}
                      />
                    </Field>
                  </Row>
                  {selectedAngle?.speculative && (
                    <div
                      className="rounded-[10px] px-3 py-2 text-[12px]"
                      style={{
                        background: "rgba(220,38,38,0.08)",
                        border: "1px solid rgba(220,38,38,0.25)",
                        color: "#dc2626",
                      }}
                    >
                      This angle is speculative. Review will flag it
                      automatically — you can still generate.
                    </div>
                  )}
                </>
              )}

              {/* Self-help */}
              {activePreset === "self_help" && (
                <>
                  <AnglePicker
                    angles={availableAngles.filter(
                      (a) => a.family === "self_help",
                    )}
                    value={angleId}
                    onChange={setAngleId}
                    label="Angle"
                  />
                  <Field label={`Tone — ${toneLabel(toneSlider)}`}>
                    <input
                      type="range"
                      min={0}
                      max={100}
                      value={toneSlider}
                      onChange={(e) => setToneSlider(Number(e.target.value))}
                      className="w-full"
                      style={{ accentColor: "var(--accent)" }}
                    />
                    <div
                      className="flex justify-between text-[10px] uppercase tracking-wide mt-1"
                      style={{ color: "var(--ink-tertiary)" }}
                    >
                      <span>Warm</span>
                      <span>Clinical</span>
                    </div>
                  </Field>
                </>
              )}

              {/* Tour recap */}
              {activePreset === "tour_recap" && (
                <>
                  <Row>
                    <Field label="Tour date">
                      <Select
                        value="red-rocks-2026-04-19"
                        onChange={() => {
                          /* mock */
                        }}
                        options={[
                          {
                            value: "red-rocks-2026-04-19",
                            label: "Red Rocks — Apr 19, 2026",
                          },
                          {
                            value: "sentrum-2026-04-02",
                            label: "Sentrum Scene — Apr 2, 2026",
                          },
                          {
                            value: "paris-2026-03-14",
                            label: "Olympia Paris — Mar 14, 2026",
                          },
                        ]}
                      />
                    </Field>
                    <Field label="Highlight type">
                      <ChipRow
                        options={[
                          { k: "crowd", label: "Crowd moment" },
                          { k: "setlist", label: "Setlist" },
                          { k: "bts", label: "BTS" },
                        ]}
                        value={tourHighlight}
                        onChange={(v) =>
                          setTourHighlight(v as "crowd" | "setlist" | "bts")
                        }
                      />
                    </Field>
                  </Row>
                </>
              )}

              {/* Fan brief — wizard for label users, mock picker for Paul-only sessions */}
              {activePreset === "fan_brief" && (
                <>
                  {labelId ? (
                    /* Wizard: pick artist + source + count, hit Create. Backend
                     edge function spins up the discover → mine → synthesize
                     pipeline and the items reconcile in Review via Realtime. */
                    <>
                      <Field label="Artist">
                        {labelArtistsQuery.isError ? (
                          <input
                            type="text"
                            value={briefArtistHandle}
                            onChange={(e) =>
                              setBriefArtistHandle(e.target.value.trim())
                            }
                            placeholder="@handle (roster fetch failed — type manually)"
                            className="w-full h-10 px-3 rounded-[10px] text-[13px] outline-none"
                            style={{
                              background: "var(--bg-subtle)",
                              color: "var(--ink)",
                              border: "1px solid var(--border)",
                            }}
                          />
                        ) : labelArtistsQuery.isLoading ? (
                          <div
                            className="rounded-[10px] px-3 py-2 text-[12px] flex items-center gap-2"
                            style={{
                              background: "var(--bg-subtle)",
                              border: "1px solid var(--border)",
                              color: "var(--ink-tertiary)",
                            }}
                          >
                            <Loader2 size={12} className="animate-spin" />
                            Loading roster…
                          </div>
                        ) : labelArtists.length === 0 ? (
                          <div
                            className="rounded-[10px] px-3 py-2 text-[12px]"
                            style={{
                              background: "var(--bg-subtle)",
                              border: "1px solid var(--border)",
                              color: "var(--ink-tertiary)",
                            }}
                          >
                            No artists in roster — see /label/admin to onboard.
                          </div>
                        ) : (
                          <Select
                            value={briefArtistHandle}
                            onChange={setBriefArtistHandle}
                            options={[
                              { value: "", label: "— pick an artist —" },
                              ...labelArtists.map((a) => ({
                                value: a.artist_handle,
                                label: `${a.artist_name} · @${a.artist_handle}`,
                              })),
                            ]}
                          />
                        )}
                      </Field>

                      <Field label="Source">
                        <ChipRow
                          options={[
                            {
                              k: "live_performance",
                              label: "Live performance",
                            },
                            { k: "podcasts", label: "Podcasts" },
                          ]}
                          value={briefSource}
                          onChange={(v) =>
                            setBriefSource(v as "live_performance" | "podcasts")
                          }
                        />
                      </Field>

                      <Field label={`Clip count — up to ${briefCount}`}>
                        <input
                          type="range"
                          min={1}
                          max={20}
                          value={briefCount}
                          onChange={(e) =>
                            setBriefCount(Number(e.target.value))
                          }
                          className="w-full"
                          style={{ accentColor: "var(--accent)" }}
                        />
                        <div
                          className="flex justify-between text-[10px] uppercase tracking-wide mt-1"
                          style={{ color: "var(--ink-tertiary)" }}
                        >
                          <span>1</span>
                          <span>20</span>
                        </div>
                      </Field>

                      <div className="flex items-center justify-between gap-3 pt-1">
                        <div
                          className="text-[11px]"
                          style={{ color: "var(--ink-tertiary)" }}
                        >
                          {!briefArtistHandle || !briefSource
                            ? "Pick an artist and a source to continue."
                            : `Discovers ${briefCount} ${
                                briefSource === "live_performance"
                                  ? "live-performance"
                                  : "podcast / interview"
                              } moment${briefCount === 1 ? "" : "s"} for @${briefArtistHandle}, mines fan-comment peaks, and lands the briefs in Review.`}
                        </div>
                        <Button
                          type="button"
                          variant="cta"
                          onClick={handleCreate}
                          disabled={
                            !briefArtistHandle || !briefSource || isCreating
                          }
                          className="px-5 text-[14px]"
                        >
                          {isCreating && (
                            <Loader2 size={14} className="animate-spin" />
                          )}
                          {isCreating ? "Submitting…" : "Create"}
                        </Button>
                      </div>
                    </>
                  ) : (
                    <>
                      <Field label="Pending brief (mock)">
                        <Select
                          value={fanBriefId}
                          onChange={(id) => {
                            setFanBriefId(id);
                            setFanBriefEdit("");
                          }}
                          options={[
                            { value: "", label: "— pick a mock brief —" },
                            ...PENDING_FAN_BRIEFS.map((b) => ({
                              value: b.id,
                              label: b.title,
                            })),
                          ]}
                        />
                      </Field>
                      <Field label="Edit hook / caption">
                        <textarea
                          value={fanBriefEdit}
                          onChange={(e) => setFanBriefEdit(e.target.value)}
                          placeholder="Mock-only — live briefs render inline with real peak_evidence when a scoped session is active."
                          className="w-full min-h-[80px] px-3 py-2 rounded-[10px] text-[14px] outline-none resize-y"
                          style={{
                            background: "var(--bg-subtle)",
                            color: "var(--ink)",
                            border: "1px solid var(--border)",
                          }}
                        />
                      </Field>
                      <div
                        className="text-[11px] flex items-center gap-1.5"
                        style={{ color: "var(--ink-tertiary)" }}
                      >
                        <span style={{ color: "var(--ink-tertiary)" }}>●</span>
                        No label scope — showing mock.
                      </div>
                    </>
                  )}
                </>
              )}

              {/* Cartoon — wizard hands off to ContentFactoryV2 which owns the
                script-stream + cartoon-vo + Realtime reconciler. The
                placeholders surface in Review with a 5-stage timeline. */}
              {activePreset === "cartoon" && (
                <CartoonPanel
                  onGenerate={onCartoonGenerate}
                  inFlightCount={cartoonsInFlight}
                />
              )}

              {/* Lyric Overlay — real generator. Mirrors the legacy
                /label/content-factory form: TikTok ref + artist handle +
                optional MP3 + transcribe provider, hands a job_id off to the
                parent which polls content-factory-status and lands the
                rendered MP4 in Review. */}
              {activePreset === "link_video" && (
                <>
                  <Field label="TikTok reference URL">
                    <input
                      type="url"
                      value={linkUrl}
                      onChange={(e) => {
                        setLinkUrl(e.target.value);
                        setLinkErrMsg(null);
                      }}
                      placeholder="https://www.tiktok.com/@creator/video/..."
                      disabled={linkSubmitting}
                      className="w-full h-10 px-3 rounded-[10px] text-[14px] outline-none"
                      style={{
                        background: "var(--bg-subtle)",
                        color: "var(--ink)",
                        border: "1px solid var(--border)",
                      }}
                    />
                    {linkUrl && !isValidTikTokUrl(linkUrl) && (
                      <div
                        className="text-[11px] mt-1"
                        style={{ color: "var(--yellow, #b45309)" }}
                      >
                        Must be a tiktok.com or vm.tiktok.com URL.
                      </div>
                    )}
                  </Field>

                  <Row>
                    <Field label="Artist handle">
                      <input
                        type="text"
                        value={linkArtistHandle}
                        onChange={(e) => {
                          setLinkArtistHandle(e.target.value);
                          setLinkErrMsg(null);
                        }}
                        placeholder="e.g. sombr"
                        disabled={linkSubmitting}
                        className="w-full h-10 px-3 rounded-[10px] text-[14px] outline-none"
                        style={{
                          background: "var(--bg-subtle)",
                          color: "var(--ink)",
                          border: "1px solid var(--border)",
                        }}
                      />
                      <div
                        className="text-[11px] mt-1"
                        style={{ color: "var(--ink-tertiary)" }}
                      >
                        Free-text — leading @ is stripped.
                      </div>
                    </Field>
                    <Field label="Transcribe provider">
                      <Select
                        value={linkTranscribeProvider}
                        onChange={(v) =>
                          setLinkTranscribeProvider(
                            v as "audioshake" | "whisperx",
                          )
                        }
                        options={[
                          {
                            value: "audioshake",
                            label: "AudioShake — premium",
                          },
                          { value: "whisperx", label: "WhisperX — free" },
                        ]}
                      />
                    </Field>
                  </Row>

                  <Field label="Artist MP3 (optional, max 10 MB)">
                    <label
                      htmlFor="cf-v2-link-mp3"
                      className="flex items-center justify-between gap-3 h-12 px-3 rounded-[10px] cursor-pointer"
                      style={{
                        background: "var(--bg-subtle)",
                        border: "1px solid var(--border)",
                        color: linkMp3File
                          ? "var(--ink)"
                          : "var(--ink-tertiary)",
                      }}
                    >
                      <span className="flex items-center gap-2 truncate">
                        <Upload size={16} />
                        <span className="truncate text-[14px]">
                          {linkMp3File ? linkMp3File.name : "Choose MP3 file"}
                        </span>
                      </span>
                      {linkMp3File && (
                        <span
                          className="text-[12px] font-['JetBrains_Mono',monospace] shrink-0"
                          style={{ color: "var(--ink-tertiary)" }}
                        >
                          {(linkMp3File.size / 1024 / 1024).toFixed(1)} MB
                        </span>
                      )}
                    </label>
                    <input
                      id="cf-v2-link-mp3"
                      type="file"
                      accept="audio/mpeg,.mp3"
                      className="hidden"
                      disabled={linkSubmitting}
                      onChange={(e) => {
                        setLinkMp3File(e.target.files?.[0] ?? null);
                        setLinkErrMsg(null);
                      }}
                    />
                    <div
                      className="text-[11px] mt-1"
                      style={{ color: "var(--ink-tertiary)" }}
                    >
                      Skip to use the sound attached to the ref TikTok.
                    </div>
                  </Field>

                  {linkErrMsg && (
                    <div
                      className="rounded-[10px] px-3 py-2 text-[13px]"
                      style={{
                        background: "rgba(220,38,38,0.08)",
                        color: "#dc2626",
                        border: "1px solid rgba(220,38,38,0.25)",
                      }}
                    >
                      {linkErrMsg}
                    </div>
                  )}

                  <div className="flex items-center justify-between gap-3 pt-1">
                    <div
                      className="text-[11px]"
                      style={{ color: "var(--ink-tertiary)" }}
                    >
                      {!labelId
                        ? "No label scope on your profile — contact Paul."
                        : !isValidTikTokUrl(linkUrl) ||
                            !stripHandle(linkArtistHandle)
                          ? "Paste a TikTok ref and an artist handle to continue."
                          : "Generates a 9:16 MP4 from the ref's vibe — ~4–8 min via content-factory-generate."}
                    </div>
                    <Button
                      type="button"
                      variant="cta"
                      onClick={() => void handleLinkVideoSubmit()}
                      disabled={
                        linkSubmitting ||
                        !labelId ||
                        !isValidTikTokUrl(linkUrl) ||
                        !stripHandle(linkArtistHandle)
                      }
                      className="px-5 text-[14px]"
                    >
                      {linkSubmitting && (
                        <Loader2 size={14} className="animate-spin" />
                      )}
                      {linkSubmitting ? "Submitting…" : "Generate"}
                    </Button>
                  </div>
                </>
              )}

              {/* Coming-soon footer for mocked presets. They render the form
                (so the URL deep-link `?preset=short_form` still resolves) but
                the Generate path is replaced with a request-access copy block.
                Backend pipelines for these aren't built yet, so the previous
                fake-QueueItem submit was just clutter. */}
              {MOCKED_PRESETS.has(activePreset) && (
                <div
                  className="rounded-xl px-4 py-3 mt-2 flex items-center justify-between gap-3"
                  style={{
                    background: "rgba(255,255,255,0.03)",
                    border: "1px dashed var(--border)",
                  }}
                >
                  <div
                    className="text-[12px]"
                    style={{ color: "var(--ink-secondary)" }}
                  >
                    <span style={{ color: "var(--ink)", fontWeight: 600 }}>
                      Coming soon —
                    </span>{" "}
                    pipeline isn't wired yet. Drop Paul a note if you need this
                    preset prioritized.
                  </div>
                </div>
              )}

              {/* Footer — Tune + Generate. Hidden for self-contained presets
                (fan-brief wizard with a label scope, cartoon panel, link →
                video form) and mocked presets (Coming-soon block above). */}
              {!(activePreset === "fan_brief" && labelId) &&
                activePreset !== "cartoon" &&
                activePreset !== "link_video" &&
                !MOCKED_PRESETS.has(activePreset) && (
                  <div className="flex items-center justify-end gap-2 pt-2">
                    <button
                      type="button"
                      onClick={() => setTuneOpen(true)}
                      className="h-10 px-4 rounded-[10px] text-[13px] font-semibold flex items-center gap-2"
                      style={{
                        background: "transparent",
                        color: "var(--ink)",
                        border: "1px solid var(--border)",
                      }}
                    >
                      <Settings2 size={14} />
                      Tune
                    </button>
                    <Button
                      type="button"
                      variant="cta"
                      onClick={handleGenerate}
                      className="px-5 text-[14px]"
                    >
                      Generate
                    </Button>
                  </div>
                )}
            </motion.section>
          )}
        </AnimatePresence>

        {!activePreset && (
          <div
            className="rounded-2xl px-5 py-8 text-center text-[13px]"
            style={{
              background: "var(--surface)",
              borderTop: "0.5px solid var(--card-edge)",
              color: "var(--ink-tertiary)",
            }}
          >
            Pick a preset above to reveal its fields.
          </div>
        )}
      </div>

      {/* Right sidebar — artist + avatar picker */}
      <aside
        className="rounded-2xl p-5 flex flex-col gap-5 h-fit"
        style={{
          background: "var(--surface)",
          borderTop: "0.5px solid var(--card-edge)",
          position: "sticky",
          top: 20,
        }}
      >
        <div>
          <SidebarLabel>Artist</SidebarLabel>
          <div className="relative">
            <select
              value={selectedArtistId}
              onChange={(e) => setSelectedArtistId(e.target.value)}
              className="w-full h-10 pl-3 pr-9 rounded-[10px] text-[13px] font-medium outline-none appearance-none cursor-pointer"
              style={{
                background: "var(--bg-subtle)",
                color: "var(--ink)",
                border: "1px solid var(--border)",
              }}
            >
              {MOCK_ARTISTS.map((a) => (
                <option key={a.id} value={a.id}>
                  {a.name}
                </option>
              ))}
            </select>
            <ChevronDown
              size={14}
              className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
              color="var(--ink-tertiary)"
            />
          </div>
          {selectedArtist && (
            <div
              className="text-[11px] font-['JetBrains_Mono',monospace] mt-1.5"
              style={{ color: "var(--ink-tertiary)" }}
            >
              {selectedArtist.handle} · {selectedArtist.labelName}
            </div>
          )}
        </div>

        <div>
          <SidebarLabel>Avatar / Soul ID</SidebarLabel>
          <div className="flex flex-col gap-1.5">
            {[
              { id: "av-native", label: "Native — artist voice" },
              { id: "av-narrator", label: "Neutral narrator" },
              { id: "av-fan", label: "Fan persona A" },
              { id: "av-fan2", label: "Fan persona B" },
            ].map((av) => (
              <button
                key={av.id}
                type="button"
                onClick={() => setSelectedAvatar(av.id)}
                className="px-3 h-9 rounded-[10px] text-left text-[13px] flex items-center gap-2"
                style={{
                  background:
                    selectedAvatar === av.id
                      ? "var(--accent-light)"
                      : "var(--bg-subtle)",
                  color:
                    selectedAvatar === av.id ? "var(--accent)" : "var(--ink)",
                  border: `1px solid ${
                    selectedAvatar === av.id ? "var(--accent)" : "var(--border)"
                  }`,
                }}
              >
                <div
                  className="w-5 h-5 rounded-full"
                  style={{
                    background:
                      selectedAvatar === av.id
                        ? "var(--accent)"
                        : "var(--border-hover, var(--border))",
                  }}
                />
                <span className="truncate">{av.label}</span>
              </button>
            ))}
          </div>
        </div>

        <div>
          <SidebarLabel>Brand kit</SidebarLabel>
          <div
            className="rounded-[10px] p-3 flex items-center gap-3"
            style={{
              background: "var(--bg-subtle)",
              border: "1px solid var(--border)",
            }}
          >
            <div className="flex gap-1">
              <Swatch color="#0b0b0c" />
              <Swatch color="#e8430a" />
              <Swatch color="#e8e2d4" />
            </div>
            <div className="min-w-0">
              <div
                className="text-[12px] font-semibold truncate"
                style={{ color: "var(--ink)" }}
              >
                {selectedArtist?.name ?? "—"} · default kit
              </div>
              <div
                className="text-[11px] truncate"
                style={{ color: "var(--ink-tertiary)" }}
              >
                DM Sans · burn-orange accent
              </div>
            </div>
          </div>
        </div>
      </aside>

      {/* Tune drawer — backdrop fade + panel slide in from the right.
          Backdrop click dismisses; e.stopPropagation on the panel keeps the
          click from leaking through. AnimatePresence so the close also
          animates instead of popping. */}
      <AnimatePresence>
        {tuneOpen && (
          <motion.div
            key="tune-backdrop"
            className="fixed inset-0 z-50 flex justify-end"
            style={{ background: "rgba(0,0,0,0.5)" }}
            onClick={() => setTuneOpen(false)}
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            transition={{ duration: 0.24, ease: [0.16, 1, 0.3, 1] }}
          >
            <motion.div
              onClick={(e) => e.stopPropagation()}
              className="h-full w-full max-w-[440px] overflow-y-auto p-6 flex flex-col gap-5"
              style={{
                background: "var(--surface)",
                borderLeft: "1px solid var(--border)",
              }}
              initial={{ x: "100%" }}
              animate={{ x: 0 }}
              exit={{ x: "100%" }}
              transition={{ duration: 0.36, ease: [0.16, 1, 0.3, 1] }}
            >
              <div className="flex items-center justify-between">
                <h2
                  className="text-[18px] font-semibold"
                  style={{ color: "var(--ink)" }}
                >
                  Tune
                </h2>
                <button
                  type="button"
                  onClick={() => setTuneOpen(false)}
                  className="w-8 h-8 rounded-lg flex items-center justify-center"
                  style={{
                    background: "var(--bg-subtle)",
                    border: "1px solid var(--border)",
                  }}
                >
                  <X size={14} color="var(--ink-tertiary)" />
                </button>
              </div>
              <p
                className="text-[12px]"
                style={{ color: "var(--ink-tertiary)" }}
              >
                Advanced knobs — every preset reads from here unless overridden
                above.
              </p>

              <TuneGroup title="AI script writer">
                <Select
                  value={scriptModel}
                  onChange={(v) =>
                    setScriptModel(
                      v as "claude-opus-4-7" | "claude-sonnet-4-6" | "gpt-5.5",
                    )
                  }
                  options={[
                    { value: "claude-opus-4-7", label: "Claude Opus 4.7" },
                    { value: "claude-sonnet-4-6", label: "Claude Sonnet 4.6" },
                    { value: "gpt-5.5", label: "GPT-5.5" },
                  ]}
                />
                <p
                  className="text-[11px] mt-2"
                  style={{ color: "var(--ink-tertiary)" }}
                >
                  Applies to every format that generates a script (cartoon,
                  real-footage, etc.). Default Opus 4.7 — switch to GPT-5.5 if
                  hooks are flat.
                </p>
              </TuneGroup>

              <TuneGroup title="Caption style">
                <ChipRow
                  options={[
                    { k: "burned_bottom", label: "Burned — bottom" },
                    { k: "karaoke", label: "Karaoke" },
                    { k: "none", label: "None" },
                  ]}
                  value="burned_bottom"
                  onChange={() => {
                    /* mock */
                  }}
                />
              </TuneGroup>

              <TuneGroup title="Voiceover model">
                <Select
                  value="opus-v1"
                  onChange={() => {
                    /* mock */
                  }}
                  options={[
                    { value: "opus-v1", label: "Opus v1 — editorial" },
                    { value: "fan-clone", label: "Fan-voice clone" },
                    { value: "elevenlabs-pro", label: "ElevenLabs Pro" },
                  ]}
                />
              </TuneGroup>

              <TuneGroup title="B-roll density">
                <input
                  type="range"
                  min={0}
                  max={100}
                  defaultValue={45}
                  className="w-full"
                  style={{ accentColor: "var(--accent)" }}
                />
              </TuneGroup>

              <TuneGroup title="Hook placement">
                <ChipRow
                  options={[
                    { k: "first_1s", label: "< 1s" },
                    { k: "first_3s", label: "< 3s" },
                    { k: "slow_build", label: "Slow build" },
                  ]}
                  value="first_3s"
                  onChange={() => {
                    /* mock */
                  }}
                />
              </TuneGroup>

              <TuneGroup title="Music bed library">
                <Select
                  value="cue_a"
                  onChange={() => {
                    /* mock */
                  }}
                  options={[
                    { value: "artist", label: "Artist catalog only" },
                    { value: "cue_a", label: "Cue library A — ambient" },
                    { value: "cue_b", label: "Cue library B — cinematic" },
                    { value: "fair_use", label: "Fair-use cleared" },
                  ]}
                />
              </TuneGroup>

              <TuneGroup title="Output format">
                <ChipRow
                  options={[
                    { k: "mp4_h264", label: "MP4 h.264" },
                    { k: "mov_prores", label: "MOV ProRes" },
                    { k: "webm", label: "WebM" },
                  ]}
                  value="mp4_h264"
                  onChange={() => {
                    /* mock */
                  }}
                />
              </TuneGroup>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}

// Validators for the Lyric Overlay form. Ported verbatim from the legacy
// /label/content-factory so the V2 entry point matches the same accepted
// input set (TikTok ref URLs only — YouTube would need a separate ingest
// path, hence the legacy hostname check).
function isValidTikTokUrl(raw: string): boolean {
  const v = raw.trim();
  if (!v) return false;
  try {
    const u = new URL(v);
    return (
      /(^|\.)tiktok\.com$/i.test(u.hostname) ||
      /(^|\.)vm\.tiktok\.com$/i.test(u.hostname)
    );
  } catch {
    return false;
  }
}

function stripHandle(input: string): string {
  return input.trim().replace(/^@+/, "");
}

function slugifyHandle(input: string): string {
  return (
    input
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/(^-|-$)/g, "")
      .slice(0, 40) || "artist"
  );
}

function buildMockTitle(
  preset: OutputType,
  artistName: string,
  angle: Angle | undefined,
  linkUrl: string,
): string {
  if (preset === "link_video") {
    const short = linkUrl ? linkUrl.slice(0, 48) : artistName;
    return `Lyric Overlay · ${short}`;
  }
  if (preset === "fan_brief") {
    return `Fan brief edit — ${artistName}`;
  }
  if (angle) {
    return `${OUTPUT_TYPE_LABEL[preset]}: ${angle.title.slice(0, 56)}`;
  }
  return `${OUTPUT_TYPE_LABEL[preset]} — ${artistName}`;
}

function toneLabel(v: number): string {
  if (v < 25) return "warm";
  if (v < 55) return "balanced";
  if (v < 80) return "reserved";
  return "clinical";
}

function SectionHeader({
  title,
  subtitle,
  tight,
}: {
  title: string;
  subtitle?: string;
  tight?: boolean;
}) {
  return (
    <div className={tight ? "" : "mb-3"}>
      <div
        className="text-[11px] font-semibold uppercase tracking-wide"
        style={{ color: "var(--ink-secondary)" }}
      >
        {title}
      </div>
      {subtitle && (
        <div
          className="text-[12px] mt-0.5"
          style={{ color: "var(--ink-tertiary)" }}
        >
          {subtitle}
        </div>
      )}
    </div>
  );
}

function SidebarLabel({ children }: { children: React.ReactNode }) {
  return (
    <div
      className="text-[10px] font-semibold uppercase tracking-wide mb-1.5"
      style={{ color: "var(--ink-secondary)" }}
    >
      {children}
    </div>
  );
}

function Field({
  label,
  children,
}: {
  label: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1.5 min-w-0">
      <label
        className="text-[11px] font-semibold uppercase tracking-wide"
        style={{ color: "var(--ink-secondary)" }}
      >
        {label}
      </label>
      {children}
    </div>
  );
}

function Row({ children }: { children: React.ReactNode }) {
  return <div className="grid grid-cols-2 gap-4">{children}</div>;
}

function Select({
  value,
  onChange,
  options,
}: {
  value: string;
  onChange: (v: string) => void;
  options: { value: string; label: string }[];
}) {
  return (
    <div className="relative">
      <select
        value={value}
        onChange={(e) => onChange(e.target.value)}
        className="w-full h-10 pl-3 pr-9 rounded-[10px] text-[13px] outline-none appearance-none cursor-pointer"
        style={{
          background: "var(--bg-subtle)",
          color: "var(--ink)",
          border: "1px solid var(--border)",
        }}
      >
        {options.map((o) => (
          <option key={o.value} value={o.value}>
            {o.label}
          </option>
        ))}
      </select>
      <ChevronDown
        size={14}
        className="absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none"
        color="var(--ink-tertiary)"
      />
    </div>
  );
}

function ChipRow({
  options,
  value,
  onChange,
}: {
  options: { k: string; label: string }[];
  value: string;
  onChange: (v: string) => void;
}) {
  return (
    <div className="flex flex-wrap gap-1.5">
      {options.map((o) => {
        const active = o.k === value;
        return (
          <button
            key={o.k}
            type="button"
            onClick={() => onChange(o.k)}
            className="px-3 h-8 rounded-[10px] text-[12px] font-semibold transition-[color,background-color,border-color,transform] duration-[var(--dur-state)] ease-[cubic-bezier(0.16,1,0.3,1)] active:scale-[0.96] active:duration-[var(--dur-instant)]"
            style={{
              background: active ? "var(--accent-light)" : "var(--bg-subtle)",
              color: active ? "var(--accent)" : "var(--ink-secondary)",
              border: `1px solid ${active ? "var(--accent)" : "var(--border)"}`,
            }}
          >
            {o.label}
          </button>
        );
      })}
    </div>
  );
}

function AnglePicker({
  angles,
  value,
  onChange,
  label = "Angle",
  allowFreeform,
}: {
  angles: Angle[];
  value: string;
  onChange: (id: string) => void;
  label?: string;
  allowFreeform?: boolean;
}) {
  if (angles.length === 0) {
    return (
      <Field label={label}>
        <div
          className="rounded-[10px] px-3 py-2 text-[12px]"
          style={{
            background: "var(--bg-subtle)",
            border: "1px solid var(--border)",
            color: "var(--ink-tertiary)",
          }}
        >
          No angles for this artist + family. Try a broader family or switch
          artists.
        </div>
      </Field>
    );
  }
  return (
    <Field label={label}>
      <Select
        value={value || ""}
        onChange={onChange}
        options={[
          ...(allowFreeform
            ? [{ value: "", label: "— freeform / no angle —" }]
            : [{ value: "", label: "— pick an angle —" }]),
          ...angles.map((a) => ({
            value: a.id,
            label: `${ANGLE_FAMILY_LABEL[a.family]} · ${a.title.slice(0, 56)}${a.title.length > 56 ? "…" : ""}`,
          })),
        ]}
      />
      {value && <AnglePreview angle={angles.find((a) => a.id === value)!} />}
    </Field>
  );
}

function AnglePreview({ angle }: { angle: Angle }) {
  const fam = ANGLE_FAMILY_COLOR[angle.family];
  return (
    <div
      className="rounded-[10px] p-3 flex flex-col gap-1.5"
      style={{
        background: "var(--bg-subtle)",
        border: "1px solid var(--border)",
      }}
    >
      <div className="flex items-center gap-2">
        <span
          className="px-2 py-0.5 rounded-full text-[10px] font-semibold uppercase tracking-wide"
          style={{ background: fam.bg, color: fam.fg }}
        >
          {ANGLE_FAMILY_LABEL[angle.family]}
        </span>
        <span
          className="text-[11px] font-['JetBrains_Mono',monospace]"
          style={{ color: "var(--ink-tertiary)" }}
        >
          {angle.sourceCount} source{angle.sourceCount === 1 ? "" : "s"}
          {angle.mostRecentSourceMonth
            ? ` · ${angle.mostRecentSourceMonth}`
            : ""}
          {angle.speculative ? " · speculative" : ""}
        </span>
      </div>
      <div
        className="text-[12px] font-semibold"
        style={{ color: "var(--ink)" }}
      >
        {angle.title}
      </div>
    </div>
  );
}

function TuneGroup({
  title,
  children,
}: {
  title: string;
  children: React.ReactNode;
}) {
  return (
    <div className="flex flex-col gap-1.5">
      <div
        className="text-[11px] font-semibold uppercase tracking-wide"
        style={{ color: "var(--ink-secondary)" }}
      >
        {title}
      </div>
      {children}
    </div>
  );
}

function Swatch({ color }: { color: string }) {
  return (
    <div
      className="w-6 h-6 rounded"
      style={{ background: color, border: "1px solid var(--border)" }}
    />
  );
}

// placeholder to prevent unused-import warnings if a preset icon is dropped later
export const __FileTextIcon = FileText;
