import { Link } from "react-router-dom";
import SEOHead from "@/components/SEOHead";

const s = {
  page: { background: "#000", minHeight: "100vh", fontFamily: "Inter, system-ui, sans-serif" } as const,
  wrap: { maxWidth: 640, margin: "0 auto", padding: "48px 24px" } as const,
  brand: { color: "#e8430a", fontSize: 20, fontWeight: 700, textDecoration: "none" } as const,
  title: { color: "rgba(255,255,255,0.87)", fontSize: 32, fontWeight: 700, margin: "32px 0 8px" } as const,
  sub: { color: "rgba(255,255,255,0.4)", fontSize: 14, margin: "0 0 48px" } as const,
  h: { color: "rgba(255,255,255,0.87)", fontSize: 18, fontWeight: 600, margin: "40px 0 12px" } as const,
  p: { color: "rgba(255,255,255,0.6)", fontSize: 16, lineHeight: 1.7, margin: "0 0 16px" } as const,
  ul: { color: "rgba(255,255,255,0.6)", fontSize: 16, lineHeight: 1.7, margin: "0 0 16px", paddingLeft: 24 } as const,
  footer: { color: "rgba(255,255,255,0.3)", fontSize: 14, textAlign: "center" as const, marginTop: 48, paddingBottom: 32 },
};

const Terms = () => (
  <div style={s.page}>
    <SEOHead
      title="Terms of Service — Wavebound"
      description="Wavebound terms of service. Read before using the app."
      canonical="/terms"
    />
    <div style={s.wrap}>
      <Link to="/" style={s.brand}>Wavebound</Link>
      <h1 style={s.title}>Terms of Service</h1>
      <p style={s.sub}>Effective March 2026</p>

      <h2 style={s.h}>1. Agreement to terms</h2>
      <p style={s.p}>By downloading, installing, or using Wavebound ("the App"), you agree to be bound by these Terms of Service. If you do not agree, do not use the App. These terms constitute a legal agreement between you and Wavebound AI ("we," "us," or "our"). We may update these terms from time to time, and continued use of the App after changes constitutes acceptance of the revised terms.</p>

      <h2 style={s.h}>2. Eligibility</h2>
      <p style={s.p}>You must be at least 13 years old to use Wavebound. If you are under 18, you represent that a parent or legal guardian has reviewed and agreed to these terms on your behalf. You must provide accurate information when creating your account. You are responsible for maintaining the security of your login credentials.</p>

      <h2 style={s.h}>3. Description of service</h2>
      <p style={s.p}>Wavebound provides AI-powered content strategy tools for music artists. The App generates content ideas, plans, and recommendations based on your artist profile and interactions. The App requires an active account provisioned by Wavebound. Access is granted on an invitation or subscription basis and may be revoked at our discretion.</p>

      <h2 style={s.h}>4. Acceptable use</h2>
      <p style={s.p}>You agree not to:</p>
      <ul style={s.ul}>
        <li>Use the App for any unlawful purpose</li>
        <li>Attempt to gain unauthorized access to the App or its systems</li>
        <li>Reverse-engineer, decompile, or disassemble the App</li>
        <li>Use the App to generate content that is defamatory, obscene, or infringes on the rights of others</li>
        <li>Share your account credentials with third parties</li>
        <li>Use automated tools to access the App beyond its intended interface</li>
      </ul>

      <h2 style={s.h}>5. Intellectual property</h2>
      <p style={s.p}>The App, including its design, code, and AI models, is owned by Wavebound AI and protected by intellectual property laws. Content ideas and plans generated by the App are provided for your use in creating content. You retain ownership of any original content you create based on these suggestions. We do not claim ownership of your music, videos, or other creative works.</p>

      <h2 style={s.h}>6. AI-generated content</h2>
      <p style={s.p}>Recommendations and content plans are generated by artificial intelligence and are suggestions only. We do not guarantee that following these suggestions will result in any particular outcome. You are solely responsible for the content you create and publish. Always review AI-generated suggestions before acting on them.</p>

      <h2 style={s.h}>7. Account termination</h2>
      <p style={s.p}>You may delete your account at any time from Profile › Delete Account. Deletion is permanent and removes all your data. We may suspend or terminate your account if you violate these terms or if we discontinue the service. We will make reasonable efforts to notify you before termination except in cases of serious violations.</p>

      <h2 style={s.h}>8. Disclaimer of warranties</h2>
      <p style={s.p}>The App is provided "as is" and "as available" without warranties of any kind, whether express or implied. We do not guarantee that the App will be uninterrupted, error-free, or that AI-generated suggestions will be accurate or suitable for your needs.</p>

      <h2 style={s.h}>9. Limitation of liability</h2>
      <p style={s.p}>To the maximum extent permitted by law, Wavebound AI shall not be liable for any indirect, incidental, special, consequential, or punitive damages arising from your use of the App. Our total liability for any claim related to the App shall not exceed the amount you paid for the service in the 12 months preceding the claim.</p>

      <h2 style={s.h}>10. Privacy</h2>
      <p style={s.p}>Your use of the App is also governed by our <Link to="/privacy" style={{ color: "#e8430a", textDecoration: "none" }}>Privacy Policy</Link>, which describes how we collect, use, and protect your data.</p>

      <h2 style={s.h}>11. Governing law</h2>
      <p style={s.p}>These terms are governed by the laws of Sweden. Any disputes arising from these terms or your use of the App shall be resolved in the courts of Stockholm, Sweden.</p>

      <h2 style={s.h}>12. Contact</h2>
      <p style={s.p}>If you have questions about these terms, email us at <a href="mailto:paul@wavebound.ai" style={{ color: "#e8430a", textDecoration: "none" }}>paul@wavebound.ai</a>.</p>

      <div style={s.footer}>© 2026 Wavebound</div>
    </div>
  </div>
);

export default Terms;
