/**
 * Complete inventory of all scripts/scrapers/workers in the Wavebound backend.
 * Cross-referenced with scraper_runs.scraper_name for status tracking.
 */

export type ScriptStatus = "active" | "inactive" | "manual" | "n8n";

export interface ScriptEntry {
  /** The scraper_name in scraper_runs (null if it doesn't log there) */
  scraper_name: string | null;
  /** Human-readable label */
  label: string;
  /** What it does (one line) */
  description: string;
  /** Category grouping */
  category: string;
  /** Cron schedule or trigger description */
  schedule: string;
  /** Which machine runs it */
  machine: string;
  /** Script path relative to scripts/ */
  script: string;
  /** Active, inactive (exists but not scheduled), manual (on-demand), n8n (workflow-triggered) */
  status: ScriptStatus;
  /** Coverage description */
  coverage?: string;
  /** Cost info */
  cost?: string;
  /** Notes (e.g. "keys 2-5 broken") */
  note?: string;
}

export const SCRIPT_INVENTORY: ScriptEntry[] = [
  // ═══ KWORB SCRAPERS ═══
  {
    scraper_name: "kworb_listeners",
    label: "Spotify Listeners",
    description: "Monthly listeners + peak listeners ranking",
    category: "Kworb",
    schedule: "4x daily (1,7,13,19 CET)",
    machine: "Main Hetzner",
    script: "kworb/scrape-listeners.ts",
    status: "active",
    coverage: "25K artists",
  },
  {
    scraper_name: "kworb_global_ranking",
    label: "Global Digital Ranking",
    description: "Global rank + per-platform points (main 300 + extended 15K)",
    category: "Kworb",
    schedule: "4x daily + daily extended",
    machine: "Main Hetzner",
    script: "kworb/scrape-global-ranking.ts",
    status: "active",
    coverage: "300 main / 15K extended",
  },
  {
    scraper_name: "kworb_country_charts",
    label: "Spotify Country Charts",
    description: "Chart positions + streams per country",
    category: "Kworb",
    schedule: "Daily 3 AM",
    machine: "Main Hetzner",
    script: "kworb/scrape-country-charts.ts",
    status: "active",
    coverage: "73 countries",
  },
  {
    scraper_name: "kworb_artist_detail",
    label: "Artist Detail (songs)",
    description: "Per-song daily_streams + total_streams, per-album streams",
    category: "Kworb",
    schedule: "Daily (6 shards)",
    machine: "All machines",
    script: "kworb/scrape-artist-detail.ts",
    status: "active",
    coverage: "25K artists, 750K songs",
  },
  {
    scraper_name: "kworb_artist_charts",
    label: "Artist Charts",
    description: "Multi-platform chart positions per song per country",
    category: "Kworb",
    schedule: "Daily overnight",
    machine: "Main Hetzner",
    script: "kworb/scrape-artist-charts.ts",
    status: "active",
    coverage: "Top 5K artists",
  },
  {
    scraper_name: "kworb_youtube",
    label: "YouTube Views + Trending",
    description: "Most-viewed, trending worldwide, per-country charts",
    category: "Kworb",
    schedule: "4x daily",
    machine: "Main Hetzner",
    script: "kworb/scrape-youtube.ts",
    status: "active",
    coverage: "Global",
  },
  {
    scraper_name: "kworb_youtube_artists",
    label: "YouTube Artist Detail",
    description: "Artist archive + detail pages (total views, video count)",
    category: "Kworb",
    schedule: "Daily overnight",
    machine: "Main Hetzner",
    script: "kworb/scrape-youtube-artists.ts",
    status: "active",
    coverage: "1.7K archive, 500 detail",
  },
  {
    scraper_name: "kworb_apple_charts",
    label: "Apple Music + iTunes Charts",
    description: "iTunes + Apple Music charts (songs + albums)",
    category: "Kworb",
    schedule: "4x daily",
    machine: "Main Hetzner",
    script: "kworb/scrape-apple-charts.ts",
    status: "active",
    coverage: "Global + EU",
  },
  {
    scraper_name: "kworb_radio",
    label: "US Radio Chart",
    description: "Billboard radio estimates + cross-platform positions",
    category: "Kworb",
    schedule: "Daily",
    machine: "Main Hetzner",
    script: "kworb/scrape-radio.ts",
    status: "active",
    coverage: "Top songs",
  },
  {
    scraper_name: "kworb_shazam",
    label: "Shazam Charts",
    description: "Shazam top songs per country",
    category: "Kworb",
    schedule: "Daily",
    machine: "Main Hetzner",
    script: "kworb/scrape-shazam-charts.ts",
    status: "active",
    coverage: "All countries",
  },
  {
    scraper_name: "kworb_tiktok",
    label: "TikTok Trending Charts",
    description: "TikTok trending charts per country",
    category: "Kworb",
    schedule: "Daily",
    machine: "Main Hetzner",
    script: "kworb/scrape-tiktok-charts.ts",
    status: "active",
    coverage: "All countries",
  },
  {
    scraper_name: null,
    label: "Platform Country Charts",
    description: "Apple/iTunes/Deezer per-country charts (songs + albums)",
    category: "Kworb",
    schedule: "Not scheduled",
    machine: "—",
    script: "kworb/scrape-platform-country-charts.ts",
    status: "inactive",
    coverage: "All available countries",
    note: "Script exists but no cron entry found",
  },

  // ═══ SCRAPECREATORS ═══
  {
    scraper_name: "tiktok_profiles",
    label: "TikTok Profiles",
    description: "Profile stats + latest videos + handle health",
    category: "ScrapeCreators",
    schedule: "Daily 4:30 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-profiles.ts",
    status: "active",
    coverage: "~10K handles",
    cost: "$0.001/call",
  },
  {
    scraper_name: "sc_tiktok_sounds",
    label: "TikTok Trending Sounds",
    description: "Trending sounds across 71 countries",
    category: "ScrapeCreators",
    schedule: "Daily 3 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-trending-sounds.ts",
    status: "active",
    coverage: "71 countries x 5 pages",
    cost: "~710 calls/run",
  },
  {
    scraper_name: "sc_tiktok_hashtags",
    label: "TikTok Trending Hashtags",
    description: "Trending hashtags across 24 countries",
    category: "ScrapeCreators",
    schedule: "Daily 3 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-trending-hashtags.ts",
    status: "active",
    coverage: "24 countries x 5 pages",
    cost: "~120 calls/run",
  },
  {
    scraper_name: "tiktok_comments",
    label: "TikTok Comments",
    description: "Staged video comments (day 1, 3, 7)",
    category: "ScrapeCreators",
    schedule: "Daily 6 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-comments.ts",
    status: "active",
    coverage: "Roster artists",
    cost: "$0.001/call",
  },
  {
    scraper_name: "tiktok_audience_geo",
    label: "TikTok Audience Geo",
    description: "Geographic audience breakdown per creator",
    category: "ScrapeCreators",
    schedule: "Daily 6 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-audience-geo.ts",
    status: "active",
    coverage: "Roster only",
    cost: "26 credits/call",
  },
  {
    scraper_name: "tiktok_sound_details",
    label: "TikTok Sound Details",
    description: "Sound metadata enrichment (user_count, chorus, matched song)",
    category: "ScrapeCreators",
    schedule: "Daily 6 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-sound-details.ts",
    status: "active",
    coverage: "Spiking sounds",
    cost: "$0.001/call",
  },
  {
    scraper_name: "tiktok_sound_videos",
    label: "TikTok Sound Videos",
    description: "Videos using trending/spiking sounds",
    category: "ScrapeCreators",
    schedule: "Daily 6 AM",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-sound-videos.ts",
    status: "active",
    coverage: "Top surging sounds",
    cost: "$0.001/call",
  },
  {
    scraper_name: "tiktok_handle_discovery",
    label: "TikTok Handle Discovery",
    description: "Discover TikTok handles via SC search",
    category: "ScrapeCreators",
    schedule: "Manual",
    machine: "Main Hetzner",
    script: "sc/scrape-tiktok-handle-discovery.ts",
    status: "manual",
    coverage: "18K artists in ~30 min",
    cost: "$0.001/call",
  },

  // ═══ FREE APIs ═══
  {
    scraper_name: "free_deezer",
    label: "Deezer",
    description: "Fan count + album count",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-deezer.ts",
    status: "active",
    coverage: "27K artists",
  },
  {
    scraper_name: "free_youtube_api",
    label: "YouTube Data API",
    description: "Channel subscriber/view/video counts",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-youtube-api.ts",
    status: "active",
    coverage: "~6K channels",
    cost: "10K quota/day",
  },
  {
    scraper_name: "free_wikipedia",
    label: "Wikipedia Pageviews",
    description: "Daily pageview history",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-wikipedia.ts",
    status: "active",
    coverage: "Top 5K",
  },
  {
    scraper_name: "free_lastfm",
    label: "Last.fm",
    description: "Artist listeners, playcount, similar artists, tags, MBID",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-lastfm.ts",
    status: "active",
    coverage: "Top 5K",
  },
  {
    scraper_name: "free_bandsintown",
    label: "Bandsintown",
    description: "Upcoming events per artist",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-bandsintown.ts",
    status: "active",
    coverage: "Top 5K",
  },
  {
    scraper_name: "free_genius",
    label: "Genius",
    description: "Artist IDs + pageview data",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-genius.ts",
    status: "active",
    coverage: "Top 5K",
  },
  {
    scraper_name: "free_musicbrainz",
    label: "MusicBrainz",
    description: "Artist metadata, cross-platform IDs, relationships",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-musicbrainz.ts",
    status: "active",
    coverage: "Batch 3K/day",
    note: "1 req/s strict rate limit — ~7 hours for 25K",
  },
  {
    scraper_name: "free_ticketmaster",
    label: "Ticketmaster",
    description: "Artist identity + touring + external links",
    category: "Free APIs",
    schedule: "Daily 4 AM",
    machine: "Main Hetzner",
    script: "free-apis/scrape-ticketmaster.ts",
    status: "active",
    coverage: "5 API keys (5K/day/key)",
    note: "Keys 2-5 returning 401 — need regeneration",
  },

  // ═══ IDENTITY RESOLUTION ═══
  {
    scraper_name: "identity_musicbrainz",
    label: "Resolve Platforms",
    description: "MusicBrainz search + enrichment → cross-platform IDs",
    category: "Identity",
    schedule: "Daily",
    machine: "Main Hetzner",
    script: "identity/resolve-platforms.ts",
    status: "active",
    coverage: "23K MBIDs (84%)",
  },
  {
    scraper_name: "identity_discography",
    label: "Harvest Discography",
    description: "MB recordings + ISRCs + release groups",
    category: "Identity",
    schedule: "Daily",
    machine: "Disco-1",
    script: "identity/harvest-discography.ts",
    status: "active",
    note: "Died during Supabase restart — relaunch needed",
  },
  {
    scraper_name: null,
    label: "Handle Health Check",
    description: "Validate handles alive/dead/changed + auto-resolve",
    category: "Identity",
    schedule: "Daily",
    machine: "Main Hetzner",
    script: "identity/check-handle-health.ts",
    status: "active",
    coverage: "200 SC calls/day budget",
  },
  {
    scraper_name: "identity_coverage_report",
    label: "Coverage Report",
    description: "Platform identity coverage scan — per-platform artist counts + gaps",
    category: "Identity",
    schedule: "Daily",
    machine: "Main Hetzner",
    script: "identity/check-coverage.ts",
    status: "active",
  },

  // ═══ PLAYLIST TRACKING ═══
  {
    scraper_name: "spotify_playlists_full",
    label: "Spotify Playlists (full)",
    description:
      "Playlist tracklists, followers, adds/removes, position changes",
    category: "Playlists",
    schedule: "Daily",
    machine: "Mac (local)",
    script: "playlist/scrape-playlists.ts",
    status: "active",
    coverage: "977 playlists, 61K tracks",
  },
  {
    scraper_name: "spotify_playlists_seed",
    label: "Spotify Playlists (seed)",
    description: "Seed playlist discovery from curated sources",
    category: "Playlists",
    schedule: "Daily",
    machine: "Mac (local)",
    script: "playlist/scrape-playlists.ts",
    status: "active",
  },
  {
    scraper_name: "spotify_playlists_discovery",
    label: "Spotify Playlists (discovery)",
    description: "Auto-discover new playlists from related artists",
    category: "Playlists",
    schedule: "Daily",
    machine: "Mac (local)",
    script: "playlist/scrape-playlists.ts",
    status: "active",
  },

  // ═══ HITL PIPELINE ═══
  {
    scraper_name: "ruben_tiktok",
    label: "Ruben (TikTok)",
    description: "SC search → discover videos → WATCH status",
    category: "HITL Pipeline",
    schedule: "Every 2h",
    machine: "Main Hetzner",
    script: "pipeline/ruben.ts",
    status: "active",
  },
  {
    scraper_name: "ruben_reels",
    label: "Ruben (Reels)",
    description: "SC reels search → discover videos → WATCH status",
    category: "HITL Pipeline",
    schedule: "Every 3h",
    machine: "Main Hetzner",
    script: "pipeline/ruben.ts",
    status: "active",
  },
  {
    scraper_name: "carl_tiktok",
    label: "Carl (TikTok)",
    description:
      "Gemini Flash thumbnail → Gemini Pro video → QUEUED_UPLOAD or DISCARD",
    category: "HITL Pipeline",
    schedule: "Every 2min",
    machine: "Main Hetzner",
    script: "pipeline/carl.ts",
    status: "active",
    cost: "Gemini API",
  },
  {
    scraper_name: "carl_reels",
    label: "Carl (Reels)",
    description: "Gemini Flash/Pro for Instagram Reels",
    category: "HITL Pipeline",
    schedule: "Every 2min",
    machine: "Main Hetzner",
    script: "pipeline/carl.ts",
    status: "active",
    cost: "Gemini API",
  },
  {
    scraper_name: "oscar_tiktok",
    label: "Oscar (TikTok)",
    description: "Profile stats → viral score → RAG upload to Storage",
    category: "HITL Pipeline",
    schedule: "Every 5min",
    machine: "Main Hetzner",
    script: "pipeline/oscar.ts",
    status: "active",
  },
  {
    scraper_name: "oscar_reels",
    label: "Oscar (Reels)",
    description: "Profile stats → viral score → RAG upload for Reels",
    category: "HITL Pipeline",
    schedule: "Every 5min",
    machine: "Main Hetzner",
    script: "pipeline/oscar.ts",
    status: "active",
  },
  {
    scraper_name: "pipeline_health",
    label: "Pipeline Health Monitor",
    description: "Detect stuck items, reset timeouts, throughput monitoring",
    category: "HITL Pipeline",
    schedule: "Every 15min",
    machine: "Main Hetzner",
    script: "pipeline/health.ts",
    status: "active",
  },

  // ═══ FAN BRIEFS ═══
  {
    scraper_name: null,
    label: "Fan Briefs — Discover",
    description: "SC YouTube search + transcription",
    category: "Fan Briefs",
    schedule: "n8n workflow",
    machine: "Main Hetzner",
    script: "fan-briefs/discover.ts",
    status: "n8n",
    cost: "ScrapeCreators",
  },
  {
    scraper_name: null,
    label: "Fan Briefs — Analyze",
    description: "Claude Opus transcript analysis → viral moments",
    category: "Fan Briefs",
    schedule: "n8n workflow",
    machine: "Main Hetzner",
    script: "fan-briefs/analyze-transcript.ts",
    status: "n8n",
    cost: "Anthropic API",
  },
  {
    scraper_name: null,
    label: "Fan Briefs — Extract",
    description: "Download clip, Gemini vision, embed, upload to Storage",
    category: "Fan Briefs",
    schedule: "n8n workflow",
    machine: "Main Hetzner",
    script: "fan-briefs/confirm-and-extract.ts",
    status: "n8n",
    cost: "Gemini API",
  },
  {
    scraper_name: null,
    label: "Fan Briefs — Generate",
    description: "Claude Opus synthesis of briefs from top segments",
    category: "Fan Briefs",
    schedule: "n8n workflow",
    machine: "Main Hetzner",
    script: "fan-briefs/generate-briefs.ts",
    status: "n8n",
    cost: "Anthropic API",
  },
  {
    scraper_name: null,
    label: "Fan Briefs — Render",
    description: "Auto-editing render (4:5 video, hook text, captions)",
    category: "Fan Briefs",
    schedule: "n8n workflow",
    machine: "Main Hetzner",
    script: "fan-briefs/render-clip.ts",
    status: "n8n",
    cost: "ffmpeg + ImageMagick",
  },

  // ═══ dbt ═══
  {
    scraper_name: "dbt_run",
    label: "dbt Run (all layers)",
    description:
      "34 models across 4 layers — orchestrates full transform pipeline",
    category: "dbt",
    schedule: "Daily after scrapers",
    machine: "Main Hetzner",
    script: "dbt/run.sh",
    status: "active",
    coverage: "34 models",
  },
  {
    scraper_name: null,
    label: "Layer 1 — Compression",
    description:
      "daily_summaries, daily_summaries_geo, song_velocity, artist_catalog_summary, playlist_momentum, instagram_artist_daily, instagram_video_summary, tiktok_artist_daily, tiktok_video_summary, tiktok_global_benchmarks",
    category: "dbt",
    schedule: "Incremental",
    machine: "Main Hetzner",
    script: "dbt/models/layer1_compression/",
    status: "active",
    coverage: "10 models",
  },
  {
    scraper_name: null,
    label: "Layer 1 — Health",
    description:
      "entity_health, song_health, market_health, platform_coverage, cross_platform_signal, discovery_streaming_divergence, geographic_footprint, market_velocity",
    category: "dbt",
    schedule: "Full rebuild",
    machine: "Main Hetzner",
    script: "dbt/models/layer1_health/",
    status: "active",
    coverage: "8 models",
  },
  {
    scraper_name: null,
    label: "Layer 1 — Anomalies",
    description: "anomalies",
    category: "dbt",
    schedule: "Full rebuild",
    machine: "Main Hetzner",
    script: "dbt/models/layer1_anomalies/",
    status: "active",
    coverage: "1 model",
  },
  {
    scraper_name: null,
    label: "Layer 2 — Intelligence",
    description:
      "artist_score, artist_momentum, artist_alerts, artist_intel_feed, artist_tiktok_profile, catalog_intelligence, catalog_tiktok_performance, cross_platform_arbitrage, market_opportunity, market_opportunity_v2, market_spillover, roster_overview, song_market_matrix, top_artist_comments, top_comments_weekly",
    category: "dbt",
    schedule: "Full rebuild",
    machine: "Main Hetzner",
    script: "dbt/models/layer2_intelligence/",
    status: "active",
    coverage: "15 models",
  },
];

export const CATEGORIES_ORDER = [
  "Kworb",
  "ScrapeCreators",
  "Free APIs",
  "Identity",
  "Playlists",
  "HITL Pipeline",
  "Fan Briefs",
  "dbt",
];
